/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * basketOrderHistoryQueryResponse schema
 */
export interface BasketOrderHistoryQueryResponse {
  /**
   * id of the basket order
   */
  basketOrderId?: number;
  /**
   * basket order name
   */
  name?: string;
  /**
   * number of creation unit
   */
  noOfCu?: number;
  /**
   * price type
   */
  priceType?: "BEST_ASK_1" | "BEST_ASK_2" | "BEST_BID_1" | "BEST_BID_2" | "ATO" | "ATC" | "LO" | "MARKET_PRICE";
  /**
   * rounding
   */
  rounding?: "UP" | "DOWN";
  /**
   * sell buy type
   */
  sellBuyType?: "SELL" | "BUY";
  /**
   * order time (yyyyMMddhhmmss)
   */
  orderTime?: string;
  /**
   * cancel time (yyyyMMddhhmmss)
   */
  cancelTime?: string;
  /**
   * status
   */
  status?: "PENDING" | "COMPLETED" | "CANCELLED";
  [k: string]: any;
}
