/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * basketOrderListResponse schema
 */
export type BasketOrderListResponse = {
  /**
   * basket order id
   */
  id?: number;
  /**
   * basket order name
   */
  name?: string;
  /**
   * is default
   */
  isDefault?: boolean;
  [k: string]: any;
}[];
