/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * basketOrderCancelRequest schema
 */
export type BasketOrderCancelRequest = BaseRequest & {
  /**
   * basket order id
   */
  basketOrderId: number;
  [k: string]: any;
};
