/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * basketOrderAddRequest schema
 */
export type BasketOrderAddRequest = BaseRequest & {
  /**
   * name
   */
  name: string;
  /**
   * basket order using to clone stock list
   */
  sourceBasketOrderId?: number;
  [k: string]: any;
};
