/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * basketOrderDetailResponse schema
 */
export type BasketOrderDetailResponse = {
  /**
   * symbol code
   */
  symbolCode?: string;
  /**
   * volume
   */
  volume?: number;
  [k: string]: any;
}[];
