/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * orderCancelRequest schema
 */
export type OrderCancelRequest = BaseRequest & {
  /**
   * order id
   */
  orderId: number;
  [k: string]: any;
};
