/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * orderHistoryResponse schema
 */
export interface OrderHistoryResponse {
  /**
   * order id
   */
  id?: number;
  /**
   * basket Order Detail Id
   */
  basketOrderDetailId?: number;
  /**
   * symbol Code
   */
  symbolCode?: string;
  /**
   * volume for 1 Cu - the full order quantity if CU = 1
   */
  volumeFor1Cu?: number;
  /**
   * order Quantity = (volumeFor1Cu)x(number of CU)
   */
  orderQuantity?: number;
  /**
   * order Price
   */
  orderPrice?: number;
  /**
   * matched Quantity
   */
  matchedQuantity?: number;
  /**
   * matched Price
   */
  matchedPrice?: number;
  /**
   * unmatched Quantity
   */
  unmatchedQuantity?: number;
  /**
   * lastest order number returned by BOS
   */
  orderNumber?: string;
  /**
   * order status
   */
  status?: "SENDING" | "PENDING" | "COMPLETED" | "CANCELLED" | "FAILED";
  /**
   * username
   */
  username?: string;
  /**
   * account Number
   */
  accountNumber?: string;
  /**
   * sub Number
   */
  subNumber?: string;
  /**
   * bank Code
   */
  bankCode?: string;
  /**
   * bank Account
   */
  bankAccount?: string;
  /**
   * sell Buy Type
   */
  sellBuyType?: "BUY" | "SELL";
  /**
   * securities Type
   */
  securitiesType?: "STOCK" | "FUND" | "ETF" | "BOND" | "FUTURES" | "CW";
  [k: string]: any;
}
