/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * orderModifyRequest schema
 */
export type OrderModifyRequest = BaseRequest & {
  /**
   * order Quantity
   */
  orderQuantity?: number;
  /**
   * order id
   */
  orderId: number;
  /**
   * order price
   */
  orderPrice?: number;
  [k: string]: any;
};
