/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * lastDividendResponse schema
 */
export interface LastDividendResponse {
  /**
   * id
   */
  id?: string;
  /**
   * symbol code
   */
  code?: string;
  /**
   * event type (DIVIDEND/PHK/RIGHT_ISSUE/BONUS_SHARE/PHCL...)
   */
  eventType?: string;
  /**
   * last exDividend date
   */
  exDividendDate?: string;
  /**
   * implement date
   */
  implementDate?: string;
  /**
   * ratio
   */
  ratio?: number;
  /**
   * price
   */
  price?: number;
  /**
   * comment
   */
  comment?: string;
  [k: string]: any;
}
