/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * newsResponse schema
 */
export interface NewsResponse {
  /**
   * id news
   */
  id?: number;
  /**
   * title of the news
   */
  title?: string;
  /**
   * content of the news
   */
  content?: string;
  /**
   * description of the news
   */
  description?: string;
  /**
   * slug of the news
   */
  slug?: string;
  /**
   * source of the news
   */
  source?: string;
  /**
   * sourceUrl of the news
   */
  sourceUrl?: string;
  /**
   * avatar of the news
   */
  avatar?: string;
  /**
   * news created at, YYYYMMDDhhmmss
   */
  createdAt?: string;
  [k: string]: any;
}
