/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * newsListRequest schema
 */
export type NewsListRequest = BaseRequest & {
  /**
   * sort, for example: 'id:desc'
   */
  sort?: string;
  /**
   * start record, offset, for example: 0
   */
  start?: number;
  /**
   * limit, fetch count, for example: 10
   */
  limit?: number;
  /**
   * fromDate (YYYYMMDD)
   */
  fromDate?: string;
  /**
   * toDate (YYYYMMDD)
   */
  toDate?: string;
  /**
   * current search Title
   */
  searchTitle?: string;
  [k: string]: any;
};
