/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * fssStopOrderCancelMultiRequest schema
 */
export type FssStopOrderCancelMultiRequest = BaseRequest & {
  /**
   * list order id to cancel
   */
  orderIdList: number[];
  /**
   * optional. Use to protect sending duplicate (only for kb)
   */
  requestId?: null | string;
  /**
   * otp (only for kb)
   */
  otpCode?: null | string;
  /**
   * transaction id (only for kb)
   */
  transactionID?: null | number;
  /**
   * channel name (only for kb)
   */
  channelName?: null | string;
  /**
   * token id (only for kb)
   */
  tokenId?: null | string;
  /**
   * pin code (only for kb)
   */
  pinCode?: null | string;
  /**
   * ca thumbPrint (only for kb)
   */
  thumbPrint?: null | string;
  /**
   * ca serial number (only for kb)
   */
  serialNumber?: null | string;
  /**
   * remember 2 factor (only for kb)
   */
  remember2Factor?: null | boolean;
  [k: string]: any;
};
