/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * fssStopOrderHistoryRequest schema
 */
export type FssStopOrderHistoryRequest = BaseRequest & {
  /**
   * account number to query
   */
  accountNumber?: string | null;
  /**
   * query filter by 1 stock
   */
  stockCode?: null | string;
  /**
   * query filter by buy or sell type
   */
  sellBuyType?: null | ("SELL" | "BUY");
  /**
   * query filter by order type
   */
  orderType?: null | ("STOP" | "STOP_LIMIT");
  /**
   * query filter by status of stop order
   */
  status?: null | ("PENDING" | "COMPLETED" | "CANCELLED" | "FAILED");
  /**
   * the sequence number of the last record, using to query next data
   */
  sequence?: null | number;
  /**
   * the number of records return for each query, default is 20
   */
  fetchCount?: null | number;
  /**
   * query order that place after or on this date, format is yyyyMMdd, default is 19700101
   */
  fromDate?: null | string;
  /**
   * query order that place before or on this date, format is yyyyMMdd, default is today
   */
  toDate?: null | string;
  [k: string]: any;
};
