/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * fssTrailingOrderHistoryRequest schema
 */
export type FssTrailingOrderHistoryRequest = BaseRequest & {
  /**
   * account number to query
   */
  accountNumber?: string | null;
  /**
   * query filter by 1 symbol code
   */
  code?: null | string;
  /**
   * query filter by buy or sell type
   */
  sellBuyType?: null | ("SELL" | "BUY");
  /**
   * query filter by status of stop order
   */
  status?: null | ("PENDING" | "COMPLETED" | "CANCELLED" | "FAILED");
  /**
   * using for query next
   */
  lastTrailingOrderId?: null | number;
  /**
   * the number of records return for each query, default is 20
   */
  fetchCount?: null | number;
  /**
   * query order that place after or on this date, format is yyyyMMdd, default is 19700101
   */
  fromDate?: null | string;
  /**
   * query order that place before or on this date, format is yyyyMMdd, default is today
   */
  toDate?: null | string;
  [k: string]: any;
};
