/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * fssTrailingOrderHistoryResponse schema
 */
export interface FssTrailingOrderHistoryResponse {
  /**
   * sequence
   */
  trailingOrderId?: number;
  /**
   * symbol code
   */
  code?: string;
  /**
   * quantity
   */
  quantity?: number;
  /**
   * sell buy type
   */
  sellBuyType?: "SELL" | "BUY";
  /**
   * trailing amount
   */
  trailingAmount?: number;
  /**
   * limit offset
   */
  limitOffset?: number;
  /**
   * current price
   */
  currentPrice?: number;
  /**
   * stop price
   */
  stopPrice?: number;
  /**
   * order number
   */
  orderNumber?: string;
  /**
   * status
   */
  status?: "PENDING" | "COMPLETED" | "CANCELLED" | "FAILED";
  /**
   * create time
   */
  createTime?: string;
  /**
   * order time
   */
  orderTime?: string;
  /**
   * cancel time
   */
  cancelTime?: string;
  /**
   * error code
   */
  errorCode?: string;
  /**
   * date, format (YYYYMMDD)
   */
  date?: null | string;
  [k: string]: any;
}
