/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * fssTrailingOrderPlaceRequest schema
 */
export type FssTrailingOrderPlaceRequest = BaseRequest & {
  /**
   * accountNumber
   */
  accountNumber: string;
  /**
   * symbol code
   */
  code: string;
  /**
   * quantity
   */
  quantity: number;
  /**
   * sellBuyType
   */
  sellBuyType: "SELL" | "BUY";
  /**
   * trailing amount (biên độ giá kích hoạt điểu chỉnh): Là điểm chênh lệnh của giá thị trường tại thời điểm hiện tại và giá kích hoạt mua.
   */
  trailingAmount: number;
  /**
   * limit offset (bước giá điều chỉnh): là bước giá chênh lệch giữa giá đặt lệnh so với giá thị trường tại thời điểm lệnh kích hoạt.
   */
  limitOffset: number;
  /**
   * date, format (YYYYMMDD); default = today
   */
  date?: null | string;
  /**
   * optional. Use to protect sending duplicate (only for kb)
   */
  requestId?: null | string;
  /**
   * otp (only for kb)
   */
  otpCode?: null | string;
  /**
   * transaction id (only for kb)
   */
  transactionID?: null | number;
  /**
   * channel name (only for kb)
   */
  channelName?: null | string;
  /**
   * token id (only for kb)
   */
  tokenId?: null | string;
  /**
   * pin code (only for kb)
   */
  pinCode?: null | string;
  /**
   * ca thumbPrint (only for kb)
   */
  thumbPrint?: null | string;
  /**
   * ca serial number (only for kb)
   */
  serialNumber?: null | string;
  /**
   * remember 2 factor (only for kb)
   */
  remember2Factor?: null | boolean;
  [k: string]: any;
};
