/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * fssTrailingOrderPlaceResponse schema
 */
export interface FssTrailingOrderPlaceResponse {
  /**
   * id of the trailingOrder that just been created
   */
  trailingOrderId?: number;
  [k: string]: any;
}
