/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * stopOrderCancelMultiRequest schema
 */
export type StopOrderCancelMultiRequest = BaseRequest & {
  /**
   * list order id to cancel
   */
  orderIdList: number[];
  [k: string]: any;
};
