/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * stopOrderHistoryResponse schema
 */
export interface StopOrderHistoryResponse {
  /**
   * sequence
   */
  sequence?: number;
  /**
   * stock code
   */
  stockCode?: string;
  /**
   * order quantity
   */
  orderQuantity?: number;
  /**
   * sell buy type
   */
  sellBuyType?: "SELL" | "BUY";
  /**
   * stop price
   */
  stopPrice?: number;
  /**
   * order type
   */
  orderType?: "STOP" | "STOP_LIMIT";
  /**
   * order price
   */
  orderPrice?: number;
  /**
   * order number
   */
  orderNumber?: string;
  /**
   * status
   */
  status?: "PENDING" | "COMPLETED" | "CANCELLED" | "FAILED";
  /**
   * create time
   */
  createTime?: string;
  /**
   * order time
   */
  orderTime?: string;
  /**
   * cancel time
   */
  cancelTime?: string;
  /**
   * bank code
   */
  bankCode?: string;
  /**
   * bank account
   */
  bankAccount?: string;
  /**
   * error message
   */
  errorMessage?: string;
  /**
   * fromDate, format (YYYYMMDD)
   */
  fromDate?: null | string;
  /**
   * toDate, format (YYYYMMDD)
   */
  toDate?: null | string;
  [k: string]: any;
}
