/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * stopOrderPlaceResponse schema
 */
export interface StopOrderPlaceResponse {
  /**
   * id of the stopOrder that just been created
   */
  id: number;
  [k: string]: any;
}
