/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * tuxedoOrderHistoryRequest schema
 */
export type TuxedoOrderHistoryRequest = BaseRequest & {
  /**
   * account Number
   */
  accountNumber: null | string;
  /**
   * sub Number
   */
  subNumber: null | string;
  /**
   * from Date
   */
  fromDate?: null | string;
  /**
   * to Date
   */
  toDate?: null | string;
  /**
   * stock Code
   */
  stockCode?: null | string;
  /**
   * sell Buy Type
   */
  sellBuyType?: null | ("SELL" | "BUY");
  /**
   * match Type
   */
  matchType?: null | string;
  /**
   * sort Type
   */
  sortType?: null | string;
  /**
   * last Order Date
   */
  lastOrderDate?: null | string;
  /**
   * last Branch Code
   */
  lastBranchCode?: null | string;
  /**
   * last Order Number
   */
  lastOrderNumber?: null | string;
  /**
   * last Match Price
   */
  lastMatchPrice?: null | number;
  /**
   * fetch Count
   */
  fetchCount?: null | number;
  /**
   * market Type
   */
  marketType?: null | string;
  [k: string]: any;
};
