/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * holiday list response
 */
export interface HolidayListResponse {
  /**
   * id of holiday
   */
  id?: number;
  /**
   * holiday (YYMMDD)
   */
  date?: string;
  /**
   * description
   */
  description?: string;
  [k: string]: any;
}
