/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * request for query list of holiday
 */
export interface LocaleKey {
  /**
   * id of key
   */
  id: number;
  /**
   * key name
   */
  key: string;
  /**
   * meaning in vietnamese
   */
  vi?: string;
  /**
   * meaning in english
   */
  en?: string;
  /**
   * meaning in korean
   */
  ko?: string;
  /**
   * meaning in chinese
   */
  cn?: string;
  /**
   * meaning in thai
   */
  th?: string;
  [k: string]: any;
}
