/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {LoginMethodStepResponse} from "./LoginMethodStepResponse";

/**
 * request for query list of holiday
 */
export interface LoginMethodResponse {
  /**
   * id
   */
  id: number;
  /**
   * normally same with domain
   */
  serviceCode: string;
  /**
   * the flow of login: password, Password_otp, password_tradex ...
   */
  grantType: string;
  /**
   * the microservice name that can handle logged in request
   */
  msName: string;
  /**
   * the uri that the logged in request should have
   */
  msUri: string;
  /**
   * is this login method is selected as default
   */
  isDefault?: boolean;
  /**
   * scope group ids belong to this login methods
   */
  scopeGroupIds?: number[];
  /**
   * mediate steps
   */
  steps?: LoginMethodStepResponse[];
  [k: string]: any;
}
