/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * intermiediate steps of login methods
 */
export interface LoginMethodStepResponse {
  /**
   * id
   */
  id: number;
  /**
   * loginMethodId
   */
  loginMethodId: number;
  /**
   * step number
   */
  step: number;
  /**
   * name for the step
   */
  name?: string;
  /**
   * description
   */
  description?: string;
  /**
   * scope group ids belong to this login methods
   */
  scopeGroupIds?: number[];
  [k: string]: any;
}
