/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * openApiListResponse schema
 */
export interface OpenApiListResponse {
  /**
   * scope Id
   */
  id?: number;
  /**
   * summary
   */
  summary?: string;
  /**
   * parameters
   */
  parameters?: {
    [k: string]: any;
  }[];
  /**
   * request Body
   */
  requestBody?: {
    [k: string]: any;
  };
  /**
   * responses
   */
  responses?: {
    [k: string]: any;
  };
  /**
   * security
   */
  security?: {
    [k: string]: any;
  }[];
  /**
   * tags
   */
  tags?: string[];
  /**
   * description
   */
  description?: string;
  [k: string]: any;
}
