/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * openApiListRequest schema
 */
export type OpenApiListRequest = BaseRequest & {
  /**
   * The number of record that user want to see at each page
   */
  fetchCount?: number | null;
  /**
   * Scope Id of the last open api queried from last time, act as next key
   */
  lastSequence?: number | null;
  [k: string]: any;
};
