/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * request for query list of holiday
 */
export type PostLocaleKeyRequest = BaseRequest & {
  /**
   * name space id
   */
  namespaceId: number;
  /**
   * key name
   */
  key: string;
  [k: string]: any;
};
