/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

import {ForwardData} from "tradex-models-common";

/**
 * request for query list of holiday
 */
export type PutAdminScopeRequest = BaseRequest & {
  /**
   * scope id to update
   */
  scopeId: number;
  /**
   * unique name of scope name
   */
  name?: string;
  /**
   * uri of api
   */
  uriPattern?: string;
  /**
   * type of forwarding
   */
  forwardType?: string;
  forwardData?: ForwardData;
  /**
   * list of scope group that scope belong to
   */
  scopeGroupIds?: number[];
  [k: string]: any;
};
