/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * request for query list of holiday
 */
export type QueryAdminScopeGroupRequest = BaseRequest & {
  /**
   * filter by name
   */
  scopeGroupName?: string;
  /**
   * offset for query
   */
  lastSequence?: number;
  /**
   * limit for query
   */
  fetchCount?: number;
  [k: string]: any;
};
