/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {ClientResponse} from "tradex-models-configuration";

/**
 * request for query list of holiday
 */
export interface QuerySystemClientResponse {
  clients?: ClientResponse[];
  lastQueriedTime?: string;
  [k: string]: any;
}
