/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {Menu} from "./Menu";

/**
 * request for query list of holiday
 */
export type QueryMenuResponse = {
  /**
   * menu id
   */
  id?: number;
  /**
   * menu name
   */
  groupName?: string;
  /**
   * sub menu
   */
  menus?: Menu[];
  [k: string]: any;
}[];
