/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * request for query list of holiday
 */
export type QuerySignedDataToUploadRequest = BaseRequest & {
  /**
   * file name
   */
  key: string;
  /**
   * type of file purpose. for determine bucket name
   */
  serviceName: string;
  [k: string]: any;
};
