/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * request for query list of holiday
 */
export type QueryLocaleKeyByNameSpaceRequest = BaseRequest & {
  /**
   * name space id
   */
  namespaceId: number;
  /**
   * how many records you want to receive
   */
  fetchCount?: number;
  /**
   * filtering the key
   */
  keyword?: string;
  /**
   * results will be after this last key ordered by key name asc
   */
  lastKey?: string;
  [k: string]: any;
};
