/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * request for query list of holiday
 */
export interface ScopeGroupResponse {
  /**
   * id
   */
  id: number;
  /**
   * normally same with domain
   */
  scopeGroupName: string;
  /**
   * scope group ids belong to this login methods
   */
  scopeIds?: number[];
  [k: string]: any;
}
