/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {ForwardData} from "tradex-models-common";

/**
 * request for query list of holiday
 */
export interface ScopeResponse {
  /**
   * id
   */
  id: number;
  /**
   * normally same with domain
   */
  name: string;
  /**
   * normally same with domain
   */
  uriPattern: string;
  /**
   * normally same with domain
   */
  forwardType: string;
  forwardData: ForwardData;
  /**
   * scope group ids belong to this login methods
   */
  scopeGroupIds?: number[];
  [k: string]: any;
}
