/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * accumulatedProfitHistoryResponse schema
 */
export interface AccumulatedProfitHistoryResponse {
  /**
   * t: time - date, like 20190101
   */
  t: number[];
  /**
   * a: accumulated profit, profit from start of strategy
   */
  a: number[];
  [k: string]: any;
}
