/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * dailyProfitHistoryResponse schema
 */
export interface DailyProfitHistoryResponse {
  /**
   * t: time - date, like 20190101
   */
  t: number[];
  /**
   * p: profit, daily profit like 100
   */
  p: number[];
  [k: string]: any;
}
