/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * dailyProfitHistoryRequest schema
 */
export type DailyProfitHistoryRequest = BaseRequest & {
  /**
   * strategyId
   */
  strategyId: number | null;
  /**
   * last date for query next, example lastDate = 20190101, query record before that day
   */
  lastDate?: number | null;
  /**
   * fetchCount
   */
  fetchCount?: number | null;
  [k: string]: any;
};
