/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * current open position response
 */
export interface OpenPositionResponse {
  /**
   * id of trading history
   */
  tradingHistoryId?: number;
  code?: string;
  /**
   * sellBuyType
   */
  openType?: "SELL" | "BUY";
  /**
   * time open position (YYYYMMDDhhmmss)
   */
  openDateTime?: string;
  /**
   * profit
   */
  profit?: number;
  /**
   * open price of position
   */
  open?: number;
  /**
   * current price
   */
  currentPrice?: number;
  [k: string]: any;
}
