/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * base request for all other
 */
export type Sample = BaseRequest & {
  param1?: string;
  param2?: number;
  param3?: boolean;
  [k: string]: any;
};
