/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * signalCancelRequest schema
 */
export type SignalCancelRequest = BaseRequest & {
  /**
   * The id of the signal got cancelled from favorite list
   */
  signalId: number | null;
  /**
   * reason why cancel
   */
  remarks?: string | null;
  [k: string]: any;
};
