/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * createSignalRequest schema
 */
export type SignalCreateRequest = BaseRequest & {
  /**
   * strategyId: Unique id of the strategy which the signal belong
   */
  strategyId: number;
  /**
   * code: code the the signal tell user to buy
   */
  code: string;
  /**
   * sellBuyType: the user should sell or buy the above code
   */
  sellBuyType: "SELL" | "BUY";
  /**
   * price: The price that user should place their order at
   */
  price: number;
  [k: string]: any;
};
