/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * signalEditRequest schema
 */
export type SignalEditRequest = BaseRequest & {
  /**
   * The id of the signal got cancelled from favorite list
   */
  signalId: number;
  /**
   * price
   */
  price?: number | null;
  /**
   * sellBuyType
   */
  sellBuyType?: "SELL" | "BUY";
  /**
   * reason why edit
   */
  remarks?: string | null;
  [k: string]: any;
};
