/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * The active Strategy request schema
 */
export type StrategyActiveRequest = BaseRequest & {
  /**
   * strategy id: The id of the strategy
   */
  strategyId: number;
  [k: string]: any;
};
