/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * Query strategy detail
 */
export type StrategyInfoRequest = BaseRequest & {
  /**
   * ID of a strategy
   */
  strategyId: number;
  [k: string]: any;
};
