/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * request for create new strategy
 */
export type StrategyAddRequest = BaseRequest & {
  /**
   * strategy name
   */
  name: string;
  /**
   * description of the strategy
   */
  description?: string | null;
  /**
   * type of the strategy
   */
  type: "EQUITY" | "DERIVATIVES";
  /**
   * expected profit of the strategy
   */
  expectedProfit?: number | null;
  /**
   * expected max drawdown of the strategy
   */
  expectedMaxDrawdown?: number | null;
  /**
   * simulation image of the strategy
   */
  simulationImage?: string | null;
  [k: string]: any;
};
