/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * response for create new strategy
 */
export interface StrategyAddResponse {
  /**
   * id of the strategy
   */
  strategyId?: number;
  [k: string]: any;
}
