/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Success response will return if the request suspend of a provider with a strategy succeed
 */
export interface StrategySuspendResponse {
  [k: string]: any;
}
