/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This is the response of subcribing a strategy
 */
export interface SubscriptionAddResponse {
  /**
   * Id of a strategy for adding subscription
   */
  strategyId?: number;
  [k: string]: any;
}
