/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * This is a request of adding new view of a strategy
 */
export type ViewAddRequest = BaseRequest & {
  /**
   * Id of a strategy for adding new view of a strategy
   */
  strategyId?: number;
  [k: string]: any;
};
