/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {AccountSub} from "./AccountSub";

/**
 * account
 */
export interface Account {
  accountNumber?: string;
  subNumber?: string;
  accountSubs?: {
    [k: string]: AccountSub;
  }[];
  [k: string]: any;
}
