/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {Bank} from "./Bank";

/**
 * sub account
 */
export interface AccountSub {
  subNumber?: string;
  type?: string;
  bankAccounts?: {
    [k: string]: Bank;
  }[];
  [k: string]: any;
}
