/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account stock balance response schema
 */
export interface AccountStockBalanceResponse {
  /**
   * Date
   */
  date?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   * Balance quantity
   */
  balanceQuantity?: null | number;
  [k: string]: any;
}
