/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Check national id request schema
 */
export type AccountCheckNationalIdRequest = {
  /**
   * identifier number
   */
  nationalId: string;
  [k: string]: any;
};
