/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * accountBalanceInfoResponse schema
 */
export interface AccountBalanceInfoResponse {
  /**
   * net Asset Value
   */
  netAssetValue?: null | number;
  /**
   * current Cash
   */
  currentCash?: null | number;
  /**
   * blocked Cash
   */
  blockedCash?: null | number;
  /**
   * unsettled Cash
   */
  unsettledCash?: null | number;
  /**
   * unpaid Dividend
   */
  unpaidDividend?: null | number;
  /**
   * total Asset
   */
  totalAsset?: null | number;
  /**
   * current Holding Value
   */
  currentHoldingValue?: null | number;
  /**
   * value Of Unpaid Rights
   */
  valueOfUnpaidRights?: null | number;
  /**
   * invested Capital
   */
  investedCapital?: null | number;
  /**
   * unrealised PL
   */
  unrealisedPL?: null | number;
  /**
   * unrealised PL Rate
   */
  unrealisedPLRate?: null | number;
  /**
   * depository Fee
   */
  depositoryFee?: null | number;
  /**
   * margin Loan
   */
  marginLoan?: null | number;
  /**
   * mortgaged Loan
   */
  mortgagedLoan?: null | number;
  /**
   * loan Interest
   */
  loanInterest?: null | number;
  /**
   * unsettled Buying Amount
   */
  unsettledBuyingAmount?: null | number;
  /**
   * total Debt
   */
  totalDebt?: null | number;
  [k: string]: any;
}
