/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account buyable response schema
 */
export interface AccountBuyableResponse {
  /**
   * Lack amount
   */
  lackAmount?: null | number;
  /**
   * Buying power
   */
  buyingPower?: null | number;
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   * Deposit amount
   */
  depositAmount?: null | number;
  /**
   * Buyable quantity
   */
  buyableQuantity?: null | number;
  /**
   * Margin limitation
   */
  marginLimitation?: null | number;
  /**
   * Order block amount
   */
  orderBlockAmount?: null | number;
  /**
   * Total block amount
   */
  totalBlockAmount?: null | number;
  /**
   * Asset valuation amount
   */
  assetValuationAmount?: null | number;
  /**
   * Stock valuation amount
   */
  stockValuationAmount?: null | number;
  /**
   * Virtual deposit amount
   */
  virtualDepositAmount?: null | number;
  [k: string]: any;
}
