/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account register response schema
 */
export interface AccountRegisterResponse {
  /**
   * branch
   */
  branch?: string;
  /**
   * visit date, format (YYYYMMDD)
   */
  visitDate?: string;
  [k: string]: any;
}
