/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * accountBalanceInfoRequest schema
 */
export type AccountBalanceInfoRequest = BaseRequest & {
  /**
   * account number
   */
  accountNumber: null | string;
  /**
   * sub number
   */
  subNumber: null | string;
  /**
   * bank code
   */
  bankCode: null | string;
  /**
   * bank account
   */
  bankAccount: null | string;
  [k: string]: any;
};
