/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account asset info response schema
 */
export interface AccountAssetInfoResponse {
  /**
   * Cmr
   */
  cmr?: null | number;
  /**
   * Rights
   */
  rights?: null | number;
  /**
   * Dividend
   */
  dividend?: null | number;
  /**
   * Interest
   */
  interest?: null | number;
  /**
   * Net asset
   */
  netAsset?: null | number;
  /**
   * Total cash
   */
  totalCash?: null | number;
  /**
   * Margin loan
   */
  marginLoan?: null | number;
  /**
   * Total asset
   */
  totalAsset?: null | number;
  /**
   * Reuse amount
   */
  reuseAmount?: null | number;
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   * Margin rights
   */
  marginRights?: null | number;
  /**
   * Available cash
   */
  availableCash?: null | number;
  /**
   * Depository fee
   */
  depositoryFee?: null | number;
  /**
   * Min buying power
   */
  minBuyingPower?: null | number;
  /**
   * Virtual deposit
   */
  virtualDeposit?: null | number;
  /**
   * Total loan amount
   */
  totalLoanAmount?: null | number;
  /**
   * Total loan buying
   */
  totalLoanBuying?: null | number;
  /**
   * Unavailable cash
   */
  unavailableCash?: null | number;
  /**
   * Cash amount for m m r
   */
  cashAmountForMMR?: null | number;
  /**
   * Evaluation amount
   */
  evaluationAmount?: null | number;
  /**
   * Evaluation rights
   */
  evaluationRights?: null | number;
  /**
   * Tl ta of margin list
   */
  tlTaOfMarginList?: null | number;
  /**
   * Stock amount for m m r
   */
  stockAmountForMMR?: null | number;
  /**
   * Total loan mortgage
   */
  totalLoanMortgage?: null | number;
  /**
   * Pending stock amount
   */
  pendingStockAmount?: null | number;
  /**
   * Tl ta of total account
   */
  tlTaOfTotalAccount?: null | number;
  /**
   * Used virtual deposit
   */
  usedVirtualDeposit?: null | number;
  /**
   * Withdrawable amount
   */
  withdrawableAmount?: null | number;
  /**
   * Lacking margin amount
   */
  lackingMarginAmount?: null | number;
  /**
   * Unmatch buying amount
   */
  unmatchBuyingAmount?: null | number;
  /**
   * Available stock amount
   */
  availableStockAmount?: null | number;
  /**
   * Stock evaluation amount
   */
  stockEvaluationAmount?: null | number;
  /**
   * Lacking loan amount for t1
   */
  lackingLoanAmountForT1?: null | number;
  /**
   * Non settled buying amount
   */
  nonSettledBuyingAmount?: null | number;
  /**
   * Unavailable stock amount
   */
  unavailableStockAmount?: null | number;
  /**
   * Stock amount can use margin
   */
  stockAmountCanUseMargin?: null | number;
  /**
   * Total loan expected amount
   */
  totalLoanExpectedAmount?: null | number;
  /**
   * Buying stock waiting amount
   */
  buyingStockWaitingAmount?: null | number;
  /**
   * Margin pending stock amount
   */
  marginPendingStockAmount?: null | number;
  /**
   * Total lacking settled amount
   */
  totalLackingSettledAmount?: null | number;
  /**
   * Margin available stock amount
   */
  marginAvailableStockAmount?: null | number;
  /**
   * Lacking virtual deposit amount
   */
  lackingVirtualDepositAmount?: null | number;
  /**
   * Evaluation pending stock amount
   */
  evaluationPendingStockAmount?: null | number;
  /**
   * Margin unavailable stock amount
   */
  marginUnavailableStockAmount?: null | number;
  /**
   * Evaluation available stock amount
   */
  evaluationAvailableStockAmount?: null | number;
  /**
   * Evaluation unavailable stock amount
   */
  evaluationUnavailableStockAmount?: null | number;
  [k: string]: any;
}
