/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account mobile response schema
 */
export interface AccountMobileResponse {
  /**
   * Phone number
   */
  phoneNumber?: null | string;
  [k: string]: any;
}
