/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Account trading summary request schema
 */
export type AccountTradingSummaryRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * From date (YYYYmmdd)
   */
  fromDate?: null | string;
  /**
   * To date (YYYYmmdd)
   */
  toDate?: null | string;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Market type, [HOSE, HNX, UPCOM, ALL]
   */
  marketType?: null | ("HOSE" | "HNX" | "UPCOM" | "ALL");
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Last match date
   */
  lastMatchDate?: null | string;
  /**
   * Last sell buy type
   */
  lastSellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Last stock code
   */
  lastStockCode?: null | string;
  /**
   * Fetch count
   */
  fetchCount?: null | number;
  [k: string]: any;
};
