/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account profit loss response schema
 */
export interface AccountProfitLossResponse {
  /**
   * Net asset
   */
  netAsset?: null | number;
  /**
   * T1 deposit
   */
  t1Deposit?: null | number;
  /**
   * T2 deposit
   */
  t2Deposit?: null | number;
  /**
   * T trade value
   */
  tTradeValue?: null | number;
  /**
   * Deposit amount
   */
  depositAmount?: null | number;
  /**
   * Total buy amount
   */
  totalBuyAmount?: null | number;
  /**
   * profitLossItems
   */
  profitLossItems?: {
    /**
     * T1 buy
     */
    t1Buy?: null | number;
    /**
     * T2 buy
     */
    t2Buy?: null | number;
    /**
     * T1 sell
     */
    t1Sell?: null | number;
    /**
     * T2 sell
     */
    t2Sell?: null | number;
    /**
     * Today buy
     */
    todayBuy?: null | number;
    /**
     * Stock code
     */
    stockCode?: null | string;
    /**
     * Today sell
     */
    todaySell?: null | number;
    /**
     * Profit loss
     */
    profitLoss?: null | number;
    /**
     * Buying price
     */
    buyingPrice?: null | number;
    /**
     * Buying amount
     */
    buyingAmount?: null | number;
    /**
     * Current price
     */
    currentPrice?: null | number;
    /**
     * Buying quantity
     */
    buyingQuantity?: null | number;
    /**
     * Profit loss rate
     */
    profitLossRate?: null | number;
    /**
     * Balance quantity
     */
    balanceQuantity?: null | number;
    /**
     * Evaluation amount
     */
    evaluationAmount?: null | number;
    /**
     * Sellable quantity
     */
    sellableQuantity?: null | number;
    [k: string]: any;
  }[];
  /**
   * Total profit loss
   */
  totalProfitLoss?: null | number;
  /**
   * Estimated deposit
   */
  estimatedDeposit?: null | number;
  /**
   * Total profit loss rate
   */
  totalProfitLossRate?: null | number;
  /**
   * Total evaluation amount
   */
  totalEvaluationAmount?: null | number;
  [k: string]: any;
}
