/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account open position response schema
 */
export interface AccountOpenPositionResponse {
  /**
   * Code
   */
  code?: null | string;
  /**
   * Next key
   */
  nextKey?: null | string;
  /**
   * Quantity
   */
  quantity?: null | number;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   * Average price
   */
  averagePrice?: null | number;
  /**
   * Current price
   */
  currentPrice?: null | number;
  /**
   * Unrealized p l
   */
  unrealizedPL?: null | number;
  /**
   * Closable quantity
   */
  closableQuantity?: null | number;
  /**
   * Previous quantity
   */
  previousQuantity?: null | number;
  [k: string]: any;
}
