/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Account profit loss request schema
 */
export type AccountProfitLossRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * base Date
   */
  baseDate?: null | string;
  /**
   * fetch Count
   */
  fetchCount?: null | number;
  /**
   * Bank name
   */
  bankName?: null | string;
  /**
   * Bank code
   */
  bankCode?: null | string;
  /**
   * Last Stock Code
   */
  lastStockCode?: null | string;
  [k: string]: any;
};
