/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Account buyable request schema
 */
export type AccountBuyableRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Bank code
   */
  bankCode?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Securities type
   */
  securitiesType?: null | string;
  /**
   * Market type, [HOSE, HNX, UPCOM, ALL]
   */
  marketType?: null | ("HOSE" | "HNX" | "UPCOM" | "ALL");
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * Order quantity
   */
  orderQuantity?: null | number;
  /**
   * Bank name
   */
  bankName?: null | string;
  [k: string]: any;
};
