/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account info response schema
 */
export interface AccountInfoResponse {
  /**
   * Email
   */
  email?: null | string;
  /**
   * Address
   */
  address?: null | string;
  /**
   * Group type
   */
  groupType?: null | string;
  /**
   * Agency code
   */
  agencyCode?: null | string;
  /**
   * Agency name
   */
  agencyName?: null | string;
  /**
   * Account type
   */
  accountType?: null | string;
  /**
   * Date of birth
   */
  dateOfBirth?: null | string;
  /**
   * Phone number
   */
  phoneNumber?: null | string;
  /**
   * Agency branch
   */
  agencyBranch?: null | string;
  /**
   * Customer name
   */
  customerName?: null | string;
  /**
   * Identifier number
   */
  identifierNumber?: null | string;
  /**
   * Representative name
   */
  representativeName?: null | string;
  /**
   * Identifier issue date
   */
  identifierIssueDate?: null | string;
  /**
   * Representative email
   */
  representativeEmail?: null | string;
  /**
   * Identifier issue place
   */
  identifierIssuePlace?: null | string;
  /**
   * Representative phone number
   */
  representativePhoneNumber?: null | string;
  /**
   * Representative identifier number
   */
  representativeIdentifierNumber?: null | string;
  [k: string]: any;
}
