/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account trading summary response schema
 */
export interface AccountTradingSummaryResponse {
  /**
   * Fee
   */
  fee?: null | number;
  /**
   * Tax
   */
  tax?: null | number;
  /**
   * Amount
   */
  amount?: null | number;
  /**
   * Match date
   */
  matchDate?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Average price
   */
  averagePrice?: null | number;
  /**
   * Match quantity
   */
  matchQuantity?: null | number;
  /**
   * Order quantity
   */
  orderQuantity?: null | number;
  /**
   * Adjusted amount
   */
  adjustedAmount?: null | number;
  /**
   * Unmatch quantity
   */
  unmatchQuantity?: null | number;
  [k: string]: any;
}
