/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Account stock balance history request schema
 */
export type AccountStockBalanceHistoryRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Last stock code
   */
  lastStockCode?: null | string;
  /**
   * Date
   */
  date: string;
  /**
   * Fetch count
   */
  fetchCount?: null | number;
  [k: string]: any;
};
