/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Place advance order response schema
 */
export interface AdvanceOrderPlaceResponse {
  /**
   * Message
   */
  message?: null | string;
  /**
   * Temp order number
   */
  tempOrderNumber?: null | string;
  [k: string]: any;
}
