/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Place adv order response schema
 */
export interface AdvOrderPlaceResponse {
  /**
   * Order number
   */
  orderNumber?: null | string;
  [k: string]: any;
}
