/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cash transfer request response schema
 */
export interface CashTransferRequestResponse {
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   * In cash balance
   */
  inCashBalance?: null | number;
  /**
   * Out cash balance
   */
  outCashBalance?: null | number;
  /**
   * Transaction date
   */
  transactionDate?: null | string;
  /**
   * In sequence number
   */
  inSequenceNumber?: null | string;
  /**
   * Out sequence number
   */
  outSequenceNumber?: null | string;
  /**
   * In previous cash balance
   */
  inPreviousCashBalance?: null | number;
  /**
   * Out previous cash balance
   */
  outPreviousCashBalance?: null | number;
  [k: string]: any;
}
