/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cash withdraw info response schema
 */
export interface CashWithdrawInfoResponse {
  /**
   * Deposit amount
   */
  depositAmount?: null | number;
  /**
   * Waiting amount
   */
  waitingAmount?: null | number;
  /**
   * Total block amount
   */
  totalBlockAmount?: null | number;
  /**
   * Deposit block amount
   */
  depositBlockAmount?: null | number;
  /**
   * Withdrawable amount
   */
  withdrawableAmount?: null | number;
  /**
   * Filling loss block amount
   */
  fillingLossBlockAmount?: null | number;
  /**
   * Maturity payment block amount
   */
  maturityPaymentBlockAmount?: null | number;
  [k: string]: any;
}
