/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cash withdraw request response schema
 */
export interface CashWithdrawRequestResponse {
  /**
   * Fee
   */
  fee?: null | number;
  /**
   * Cash balance
   */
  cashBalance?: null | number;
  /**
   * Received cash
   */
  receivedCash?: null | number;
  /**
   * Sequence number
   */
  sequenceNumber?: null | string;
  /**
   * Transaction date
   */
  transactionDate?: null | string;
  /**
   * Previous cash balance
   */
  previousCashBalance?: null | number;
  [k: string]: any;
}
