/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * query list country code response schema
 */
export interface CountryCodeListReponse {
  /**
   * Country Name
   */
  name?: string;
  /**
   * Country Code
   */
  code?: string;
  [k: string]: any;
}
