/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Account open position request schema
 */
export type DrAccountOpenPositionRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Last next key
   */
  lastNextKey?: null | string;
  /**
   * Fetch count
   */
  fetchCount?: null | number;
  /**
   * Password
   */
  password?: null | string;
  /**
   * Branch code
   */
  branchCode?: null | string;
  /**
   * Agency code
   */
  agencyCode?: null | string;
  /**
   * User name
   */
  userName?: null | string;
  [k: string]: any;
};
