/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr order unmatch position request schema
 */
export type DrAccountUnmatchPositionRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Password
   */
  password?: null | string;
  /**
   * Code
   */
  code?: null | string;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Limit price
   */
  limitPrice?: null | number;
  /**
   * Order type
   */
  orderType?: null | string;
  /**
   * Stop price
   */
  stopPrice?: null | number;
  [k: string]: any;
};
