/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dr account trading limit response schema
 */
export interface DrAccountTradingLimitResponse {
  /**
   * Code
   */
  code?: null | string;
  /**
   * Next key
   */
  nextKey?: null | string;
  /**
   * Tick limit
   */
  tickLimit?: null | number;
  /**
   * Account name
   */
  accountName?: null | string;
  /**
   * Tick limit yn
   */
  tickLimitYn?: boolean;
  /**
   * Trading limit
   */
  tradingLimit?: null | number;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Trading limit yn
   */
  tradingLimitYn?: boolean;
  /**
   * Use trading limit yn
   */
  useTradingLimitYn?: boolean;
  [k: string]: any;
}
