/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Account profit loss request schema
 */
export type DrAccountPLRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * from Date
   */
  fromDate?: null | string;
  /**
   * to Date
   */
  toDate?: null | string;
  /**
   * fetch Count
   */
  fetchCount?: null | number;
  /**
   * last Next Key
   */
  lastNextKey?: null | string;
  [k: string]: any;
};
