/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account summary response schema
 */
export interface DrAccountSummaryResponse {
  /**
   *  c a a
   */
  CAA?: null | number;
  /**
   * Fee
   */
  fee?: null | number;
  /**
   * Tax
   */
  tax?: null | number;
  /**
   * Date
   */
  date?: null | string;
  /**
   * Realized p l
   */
  realizedPL?: null | number;
  /**
   * Assigned fee
   */
  assignedFee?: null | number;
  /**
   * In out amount
   */
  inOutAmount?: null | number;
  /**
   * Unrealized p l
   */
  unrealizedPL?: null | number;
  /**
   * Margin deficit
   */
  marginDeficit?: null | number;
  /**
   * Today cash balance
   */
  todayCashBalance?: null | number;
  /**
   * Margin requirement
   */
  marginRequirement?: null | number;
  /**
   * Margin utilization
   */
  marginUtilization?: null | number;
  /**
   * Previous cash balance
   */
  previousCashBalance?: null | number;
  /**
   * Asset collateral value
   */
  assetCollateralValue?: null | number;
  /**
   * Pending withdrawal c a a
   */
  pendingWithdrawalCAA?: null | number;
  /**
   * Sec margin requirement
   */
  secMarginRequirement?: null | number;
  /**
   * Available fund for order
   */
  availableFundForOrder?: null | number;
  /**
   * Pending withdrawal amount
   */
  pendingWithdrawalAmount?: null | number;
  /**
   * Available fund for withdraw
   */
  availableFundForWithdraw?: null | number;
  /**
   * Available fund for withdraw c a a
   */
  availableFundForWithdrawCAA?: null | number;
  /**
   * Unmatched order margin requirement
   */
  unmatchedOrderMarginRequirement?: null | number;
  [k: string]: any;
}
