/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account risk ratio response schema
 */
export interface DrAccountRiskRatioResponse {
  /**
   * Position
   */
  position?: null | number;
  /**
   * Margin level
   */
  marginLevel?: null | string;
  /**
   * Spread margin
   */
  spreadMargin?: null | number;
  /**
   * Initial margin
   */
  initialMargin?: null | number;
  /**
   * Variation margin
   */
  variationMargin?: null | number;
  /**
   * Margin requirement
   */
  marginRequirement?: null | number;
  /**
   * Margin utilization
   */
  marginUtilization?: null | number;
  /**
   * Initial margin delivery
   */
  initialMarginDelivery?: null | number;
  /**
   * Accepted collateral value
   */
  acceptedCollateralValue?: null | number;
  [k: string]: any;
}
