/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account profit loss response schema
 */
export interface DrAccountPLResponse {
  /**
   * closedLongQuantity
   */
  closedLongQuantity?: null | number;
  /**
   * closedShortQuantity
   */
  closedShortQuantity?: null | number;
  /**
   * realizedPL
   */
  realizedPL?: null | number;
  /**
   * T trade value
   */
  tTradeValue?: null | number;
  /**
   * fee
   */
  fee?: null | number;
  /**
   * tax
   */
  tax?: null | number;
  /**
   * netProfitLoss
   */
  netProfitLoss?: null | number;
  /**
   * long Quantity
   */
  longQuantity?: null | number;
  /**
   * short Quantity
   */
  shortQuantity?: null | number;
  /**
   * unrealized PL
   */
  unrealizedPL?: null | number;
  /**
   * profitLossItems
   */
  profitLossItems?: {
    /**
     * code
     */
    code?: null | number;
    /**
     * last Price
     */
    lastPrice?: null | number;
    /**
     * closed Long Quantity
     */
    closedLongQuantity?: null | number;
    /**
     * closed Short Quantity
     */
    closedShortQuantity?: null | number;
    /**
     * realized PL
     */
    realizedPL?: null | number;
    /**
     * fee
     */
    fee?: null | string;
    /**
     * tax
     */
    tax?: null | number;
    /**
     * net Profit Loss
     */
    netProfitLoss?: null | number;
    /**
     * long Quantity
     */
    longQuantity?: null | number;
    /**
     * short Quantity
     */
    shortQuantity?: null | number;
    /**
     * unrealized PL
     */
    unrealizedPL?: null | number;
    /**
     * next Key
     */
    nextKey?: null | number;
    [k: string]: any;
  }[];
  [k: string]: any;
}
