/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account equity response schema
 */
export interface DrAccountEquityResponse {
  /**
   * Total cash balance
   */
  totalCashBalance?: null | number;
  /**
   * Total stock amount
   */
  totalStockAmount?: null | number;
  /**
   * Total stock quantity
   */
  totalStockQuantity?: null | number;
  /**
   * Available cash balance
   */
  availableCashBalance?: null | number;
  /**
   * Available stock amount
   */
  availableStockAmount?: null | number;
  /**
   * Available stock quantity
   */
  availableStockQuantity?: null | number;
  [k: string]: any;
}
