/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Cash withdraw request request schema
 */
export type DrCashWithdrawRequestRequest = BaseRequest & {
  /**
   * Note
   */
  note?: null | string;
  /**
   * Amount
   */
  amount: number;
  /**
   * Bank code
   */
  bankCode?: null | string;
  /**
   * Bank account
   */
  bankAccount: string;
  /**
   * Account number
   */
  accountNumber: string;
  [k: string]: any;
};
