/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * History position response schema
 */
export interface DrHistoryPositionResponse {
  /**
   * Code
   */
  code?: null | string;
  /**
   * User id
   */
  userId?: null | string;
  /**
   * Next key
   */
  nextKey?: null | string;
  /**
   * Quantity
   */
  quantity?: null | number;
  /**
   * Last price
   */
  lastPrice?: null | number;
  /**
   * Match price
   */
  matchPrice?: null | number;
  /**
   * Account name
   */
  accountName?: null | string;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Trading date
   */
  tradingDate?: null | string;
  /**
   * Maturity date
   */
  maturityDate?: null | string;
  /**
   * Unrealized p l
   */
  unrealizedPL?: null | number;
  /**
   * Account number
   */
  accountNumber?: null | string;
  [k: string]: any;
}
