/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dr history closed position response schema
 */
export interface DrHistoryClosedPositionResponse {
  /**
   * Next key
   */
  nextKey?: null | string;
  /**
   * Total fee
   */
  totalFee?: null | number;
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   * Total quantity
   */
  totalQuantity?: null | number;
  /**
   * Total realized pl
   */
  totalRealizedPl?: null | number;
  /**
   * Total net profit loss
   */
  totalNetProfitLoss?: null | number;
  /**
   * Closed position items
   */
  closedPositionItems?: {
    /**
     * Code
     */
    code?: null | string;
    /**
     * User id
     */
    userId?: null | string;
    /**
     * Next key
     */
    nextKey?: null | string;
    /**
     * Buy price
     */
    buyPrice?: null | number;
    /**
     * Close date
     */
    closeDate?: null | string;
    /**
     * Sell price
     */
    sellPrice?: null | number;
    /**
     * Commission
     */
    commission?: null | string;
    /**
     * Realized pl
     */
    realizedPl?: null | number;
    /**
     * Account name
     */
    accountName?: null | string;
    /**
     * Account number
     */
    accountNumber?: null | string;
    /**
     * Net profit loss
     */
    netProfitLoss?: null | string;
    /**
     * Matched quantity
     */
    matchedQuantity?: null | number;
    [k: string]: any;
  }[];
  [k: string]: any;
}
