/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * History margin call response schema
 */
export interface DrHistoryMarginCallResponse {
  /**
   * Date
   */
  date?: null | string;
  /**
   * Next key
   */
  nextKey?: null | string;
  /**
   * Is resolved
   */
  isResolved?: boolean;
  /**
   * Assigned c a a
   */
  assignedCAA?: null | number;
  /**
   * Margin amount
   */
  marginAmount?: null | number;
  /**
   * Net margin call
   */
  netMarginCall?: null | number;
  /**
   * Deposit balance
   */
  depositBalance?: null | number;
  /**
   * Margin requirement
   */
  marginRequirement?: null | number;
  /**
   * Previous assigned c a a
   */
  previousAssignedCAA?: null | number;
  /**
   * Previous margin deficit
   */
  previousMarginDeficit?: null | number;
  /**
   * Previous deposit balance
   */
  previousDepositBalance?: null | number;
  [k: string]: any;
}
