/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * History settlement response schema
 */
export interface DrHistorySettlementResponse {
  /**
   * Fee
   */
  fee?: null | number;
  /**
   * Tax
   */
  tax?: null | number;
  /**
   * Total fee
   */
  totalFee?: null | number;
  /**
   * Fee status
   */
  feeStatus?: boolean;
  /**
   * Tax status
   */
  taxStatus?: boolean;
  /**
   * Settle date
   */
  settleDate?: null | string;
  /**
   * Trading date
   */
  tradingDate?: null | string;
  /**
   * Deficit amount
   */
  deficitAmount?: null | number;
  /**
   * Deposit balance
   */
  depositBalance?: null | number;
  /**
   * Variation margin
   */
  variationMargin?: null | number;
  /**
   * Variation margin status
   */
  variationMarginStatus?: boolean;
  [k: string]: any;
}
