/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dr history trade response schema
 */
export interface DrHistoryTradeResponse {
  /**
   * Items
   */
  items?: {
    /**
     * Tax
     */
    tax?: null | number;
    /**
     * Code
     */
    code?: null | string;
    /**
     * User id
     */
    userId?: null | string;
    /**
     * User ip
     */
    userIp?: null | string;
    /**
     * Order date
     */
    orderDate?: null | string;
    /**
     * Commission
     */
    commission?: null | string;
    /**
     * Account name
     */
    accountName?: null | string;
    /**
     * Order number
     */
    orderNumber?: null | string;
    /**
     * Sell buy type, [BUY, SELL, ALL]
     */
    sellBuyType?: null | ("BUY" | "SELL" | "ALL");
    /**
     * Trading date
     */
    tradingDate?: null | string;
    /**
     * Matched price
     */
    matchedPrice?: null | number;
    /**
     * Account number
     */
    accountNumber?: null | string;
    /**
     * Order quantity
     */
    orderQuantity?: null | number;
    /**
     * Trading amount
     */
    tradingAmount?: null | number;
    /**
     * Trading channel
     */
    tradingChannel?: null | string;
    /**
     * Matched quantity
     */
    matchedQuantity?: null | number;
    /**
     * Original order number
     */
    originalOrderNumber?: null | string;
    [k: string]: any;
  }[];
  /**
   * Next key
   */
  nextKey?: null | string;
  /**
   * Total fee
   */
  totalFee?: null | number;
  /**
   * Total tax
   */
  totalTax?: null | number;
  /**
   * Total quantity
   */
  totalQuantity?: null | number;
  /**
   * Total buy quantity
   */
  totalBuyQuantity?: null | number;
  /**
   * Total sell quantity
   */
  totalSellQuantity?: null | number;
  [k: string]: any;
}
