/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Transfer im history response schema
 */
export interface DrImHistoryResponse {
  /**
   * Note
   */
  note?: null | string;
  /**
   * Amount
   */
  amount?: null | number;
  /**
   * Dest bank
   */
  destBank?: null | string;
  /**
   * Is cancel
   */
  isCancel?: boolean;
  /**
   * Bos status
   */
  bosStatus?: null | string;
  /**
   * Fee amount
   */
  feeAmount?: null | number;
  /**
   * Vsd status
   */
  vsdStatus?: null | string;
  /**
   * Bank status
   */
  bankStatus?: null | string;
  /**
   * Source bank
   */
  sourceBank?: null | string;
  /**
   * Received amount
   */
  receivedAmount?: null | number;
  /**
   * Sequence number
   */
  sequenceNumber?: null | string;
  /**
   * Transaction date
   */
  transactionDate?: null | string;
  /**
   * Transaction type
   */
  transactionType?: null | string;
  [k: string]: any;
}
