/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Transfer im fee response schema
 */
export interface DrImFeeResponse {
  /**
   * Fee type
   */
  feeType?: null | string;
  /**
   * Fee amount
   */
  feeAmount?: null | number;
  /**
   * Adjusted amount
   */
  adjustedAmount?: null | number;
  /**
   * Received amount
   */
  receivedAmount?: null | number;
  [k: string]: any;
}
