/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Transfer im withdraw request request schema
 */
export type DrImWithdrawRequestRequest = BaseRequest & {
  /**
   * Note
   */
  note?: null | string;
  /**
   * Amount
   */
  amount: number;
  /**
   * Fee type
   */
  feeType: string;
  /**
   * Dest bank
   */
  destBank: string;
  /**
   * Fee amount
   */
  feeAmount: number;
  /**
   * Source bank
   */
  sourceBank: string;
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Adjusted amount
   */
  adjustedAmount: number;
  /**
   * Received amount
   */
  receivedAmount: number;
  [k: string]: any;
};
