/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Transfer im bank response schema
 */
export interface DrImBankResponse {
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   * Bank account name
   */
  bankAccountName?: null | string;
  /**
   * Bank account number
   */
  bankAccountNumber?: null | string;
  [k: string]: any;
}
