/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Transfer im bank request schema
 */
export type DrImBankRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Type
   */
  type: "DEPOSIT_FROM" | "DEPOSIT_TO" | "WITHDRAW_FROM" | "WITHDRAW_TO";
  [k: string]: any;
};
