/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Transfer im fee request schema
 */
export type DrImFeeRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Sending bank
   */
  sendingBank: string;
  /**
   * Receiving bank
   */
  receivingBank: string;
  /**
   * Amount
   */
  amount: number;
  /**
   * Type
   */
  type: string;
  [k: string]: any;
};
