/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr modify normal order request schema
 */
export type DrModifyNormalOrderRequest = BaseRequest & {
  /**
   * Code
   */
  code?: null | string;
  /**
   * Heg yn
   */
  hegYn?: null | string;
  /**
   * Reg yn
   */
  regYn?: null | string;
  /**
   * Password
   */
  password?: null | string;
  /**
   * Validity
   */
  validity?: null | string;
  /**
   * Order type
   */
  orderType?: null | string;
  /**
   * Stop price
   */
  stopPrice?: null | string;
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * Order number
   */
  orderNumber?: null | string;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Order quantity
   */
  orderQuantity?: null | number;
  /**
   * Unmatched quantity
   */
  unmatchedQuantity?: null | number;
  [k: string]: any;
};
