/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr query order match request schema
 */
export type DrOrderMatchRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber?: string;
  /**
   * Password
   */
  password?: string;
  /**
   * Favorite list group name
   */
  favoriteListGroupName?: string;
  /**
   * Last next key
   */
  lastNextKey?: string;
  /**
   * Fetch count
   */
  fetchCount?: number;
  [k: string]: any;
};
