/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dr order today unmatch response schema
 */
export interface DrOrderTodayUnmatchResponse {
  /**
   * Code
   */
  code?: null | string;
  /**
   * Next key
   */
  nextKey?: null | string;
  /**
   * Validity
   */
  validity?: null | string;
  /**
   * Order type
   */
  orderType?: null | string;
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * Order style
   */
  orderStyle?: null | string;
  /**
   * Account name
   */
  accountName?: null | string;
  /**
   * Order number
   */
  orderNumber?: null | string;
  /**
   * Order status
   */
  orderStatus?: null | string;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Strategy type
   */
  strategyType?: null | string;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Order quantity
   */
  orderQuantity?: null | number;
  /**
   * Matched quantity
   */
  matchedQuantity?: null | number;
  /**
   * Unmatched quantity
   */
  unmatchedQuantity?: null | number;
  [k: string]: any;
}
