/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dr order history response schema
 */
export interface DrOrderHistoryResponse {
  /**
   * Code
   */
  code?: string;
  /**
   * Heg yn
   */
  hegYn?: string;
  /**
   * User id
   */
  userId?: string;
  /**
   * Next key
   */
  nextKey?: string;
  /**
   * Validity
   */
  validity?: string;
  /**
   * Order date
   */
  orderDate?: string;
  /**
   * Order time
   */
  orderTime?: string;
  /**
   * Order type
   */
  orderType?: string;
  /**
   * Order price
   */
  orderPrice?: number;
  /**
   * Order style
   */
  orderStyle?: string;
  /**
   * Account name
   */
  accountName?: string;
  /**
   * Order number
   */
  orderNumber?: string;
  /**
   * Sell buy type
   */
  sellBuyType?: string;
  /**
   * Strategy type
   */
  strategyType?: string;
  /**
   * Account number
   */
  accountNumber?: string;
  /**
   * Order quantity
   */
  orderQuantity?: number;
  /**
   * Cancel quantity
   */
  cancelQuantity?: number;
  /**
   * Matched quantity
   */
  matchedQuantity?: number;
  /**
   * Modify cancel type
   */
  modifyCancelType?: string;
  /**
   * Rejection message
   */
  rejectionMessage?: string;
  /**
   * Unmatched quantity
   */
  unmatchedQuantity?: number;
  /**
   * Original order number
   */
  originalOrderNumber?: string;
  [k: string]: any;
}
