/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr order stop cancel request schema
 */
export type DrOrderStopCancelRequest = BaseRequest & {
  /**
   * Password
   */
  password?: null | string;
  /**
   * Created date
   */
  createdDate?: null | string;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Sequence number
   */
  sequenceNumber?: null | string;
  [k: string]: any;
};
