/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dr place adv order response schema
 */
export interface DrOrderAdvPlaceResponse {
  /**
   * Order number
   */
  orderNumber?: string;
  [k: string]: any;
}
