/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr order available request schema
 */
export type DrOrderAvailableRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Password
   */
  password?: null | string;
  /**
   * Code
   */
  code: string;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * order type
   */
  orderType?: null | string;
  [k: string]: any;
};
