/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dr order adv history response schema
 */
export interface DrOrderAdvHistoryResponse {
  /**
   * Ip
   */
  ip?: null | string;
  /**
   * Code
   */
  code?: null | string;
  /**
   * Date
   */
  date?: null | string;
  /**
   * Is sent
   */
  isSent?: boolean;
  /**
   * Send yn
   */
  sendYn?: null | string;
  /**
   * To date
   */
  toDate?: null | string;
  /**
   * Is valid
   */
  isValid?: boolean;
  /**
   * Mdm type
   */
  mdmType?: null | string;
  /**
   * Next key
   */
  nextKey?: null | string;
  /**
   * Code name
   */
  codeName?: null | string;
  /**
   * From date
   */
  fromDate?: null | string;
  /**
   * Operator
   */
  operator?: null | string;
  /**
   * Username
   */
  username?: null | string;
  /**
   * Validity
   */
  validity?: null | string;
  /**
   * Error code
   */
  errorCode?: null | string;
  /**
   * Order type
   */
  orderType?: null | string;
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * Register yn
   */
  registerYn?: null | string;
  /**
   * Account name
   */
  accountName?: null | string;
  /**
   * Order number
   */
  orderNumber?: null | string;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   * Valid status
   */
  validStatus?: null | string;
  /**
   * Error message
   */
  errorMessage?: null | string;
  /**
   * Is registered
   */
  isRegistered?: boolean;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Market session
   */
  marketSession?: null | string;
  /**
   * Matched status
   */
  matchedStatus?: null | string;
  /**
   * Operating time (HHMMSS)
   */
  operatingTime?: null | string;
  /**
   * Order quantity
   */
  orderQuantity?: null | number;
  /**
   * Cancel date time
   */
  cancelDateTime?: null | string;
  /**
   * Cancel modify id
   */
  cancelModifyId?: null | string;
  /**
   * Cancel username
   */
  cancelUsername?: null | string;
  /**
   * Registered date
   */
  registeredDate?: null | string;
  /**
   * Sequence number
   */
  sequenceNumber?: null | string;
  /**
   * Matched quantity
   */
  matchedQuantity?: null | number;
  /**
   * Order send status
   */
  orderSendStatus?: null | string;
  /**
   * Advance order type
   */
  advanceOrderType?: null | string;
  /**
   * Cancel modify time
   */
  cancelModifyTime?: null | string;
  /**
   * Roll over quantity
   */
  rollOverQuantity?: null | number;
  /**
   * Unmatched quantity
   */
  unmatchedQuantity?: null | number;
  /**
   * Average matched price
   */
  averageMatchedPrice?: null | number;
  /**
   * Modify cancel quantity
   */
  modifyCancelQuantity?: null | number;
  [k: string]: any;
}
