/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr order adv history request schema
 */
export type DrOrderAdvHistoryRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Password
   */
  password?: null | string;
  /**
   * Advance order type
   */
  advanceOrderType?: null | string;
  /**
   * From date (YYYYmmdd)
   */
  fromDate?: null | string;
  /**
   * To date (YYYYmmdd)
   */
  toDate?: null | string;
  /**
   * Register type
   */
  registerType?: null | string;
  /**
   * Order send
   */
  orderSend?: null | string;
  /**
   * Matched status
   */
  matchedStatus?: null | string;
  /**
   * Validity
   */
  validity?: null | string;
  /**
   * Branch code
   */
  branchCode?: null | string;
  /**
   * Agency code
   */
  agencyCode?: null | string;
  /**
   * Contract code
   */
  contractCode?: null | string;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Roll over type
   */
  rollOverType?: null | string;
  /**
   * Last next key
   */
  lastNextKey?: null | string;
  /**
   * Fetch count
   */
  fetchCount?: null | number;
  [k: string]: any;
};
