/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dr order unmatch position response schema
 */
export interface DrOrderUnmatchPositionResponse {
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   *  unmatched buy quantity
   */
  UnmatchedBuyQuantity?: null | number;
  /**
   *  unmatched sell quantity
   */
  UnmatchedSellQuantity?: null | number;
  /**
   * Non settled buy quantity
   */
  nonSettledBuyQuantity?: null | number;
  /**
   * Non settled sell quantity
   */
  nonSettledSellQuantity?: null | number;
  [k: string]: any;
}
