/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dr query order match response schema
 */
export interface DrOrderMatchResponse {
  /**
   * Account number
   */
  accountNumber?: string;
  /**
   * Account name
   */
  accountName?: string;
  /**
   * Order number
   */
  orderNumber?: string;
  /**
   * Code
   */
  code?: string;
  /**
   * Sell buy type
   */
  sellBuyType?: string;
  /**
   * Match price
   */
  matchPrice?: number;
  /**
   * Matched quantity
   */
  matchedQuantity?: number;
  /**
   * Unmatched quantity
   */
  unmatchedQuantity?: number;
  /**
   * Time
   */
  time?: string;
  /**
   * Liquidation position number
   */
  liquidationPositionNumber?: number;
  /**
   * Next key
   */
  nextKey?: string;
  [k: string]: any;
}
