/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dr order modify all response schema
 */
export interface DrOrderModifyAllResponse {
  /**
   * Message
   */
  message?: null | string;
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  [k: string]: any;
}
