/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dr order stop response schema
 */
export interface DrOrderStopResponse {
  /**
   * Dummy
   */
  dummy?: null | string;
  [k: string]: any;
}
