/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Derivatives modify order request schema
 */
export type DrOrderModifyRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * code
   */
  code?: null | string;
  /**
   * Order quantity
   */
  orderQuantity: number;
  /**
   * Order price
   */
  orderPrice: number;
  /**
   * Order number
   */
  orderNumber: string;
  /**
   * Order type, [LO , MP , ATO , ATC , AON , BIG_LOT , MOK , MAK , MTL , IO , SO_GREATER , SO_LESS , SBO , OBO , PLO , ALL]
   */
  orderType?:
    | "LO"
    | "MP"
    | "ATO"
    | "ATC"
    | "AON"
    | "BIG_LOT"
    | "MOK"
    | "MAK"
    | "MTL"
    | "IO"
    | "SO_GREATER"
    | "SO_LESS"
    | "SBO"
    | "OBO"
    | "PLO"
    | "ALL";
  /**
   * unmatched Quantity
   */
  unmatchedQuantity?: null | number;
  /**
   * password
   */
  password?: null | string;
  /**
   * validity
   */
  validity?: null | string;
  /**
   * stopPrice
   */
  stopPrice?: number;
  /**
   * regYn
   */
  regYn?: string;
  /**
   * hegYn
   */
  hegYn?: string;
  [k: string]: any;
};
