/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr cancel adv order request schema
 */
export type DrOrderAdvCancelRequest = BaseRequest & {
  /**
   * Code
   */
  code: string;
  /**
   * Order number
   */
  orderNumber: string;
  /**
   * Trading date
   */
  tradingDate: string;
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Market session
   */
  marketSession: string;
  [k: string]: any;
};
