/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr place adv order request schema
 */
export type DrOrderAdvPlaceRequest = BaseRequest & {
  /**
   * Code
   */
  code?: null | string;
  /**
   * To date
   */
  toDate?: null | string;
  /**
   * From date
   */
  fromDate?: null | string;
  /**
   * Order type
   */
  orderType?: null | string;
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * Sell buy type
   */
  sellBuyType?: null | string;
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Market session
   */
  marketSession?: null | string;
  /**
   * Order quantity
   */
  orderQuantity?: null | number;
  /**
   * Advance order type
   */
  advanceOrderType?: null | string;
  [k: string]: any;
};
