/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr order stop history request schema
 */
export type DrOrderStopHistoryRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Password
   */
  password?: null | string;
  /**
   * From date (YYYYmmdd)
   */
  fromDate?: null | string;
  /**
   * To date (YYYYmmdd)
   */
  toDate?: null | string;
  /**
   * Contact code
   */
  contactCode?: null | string;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Order type
   */
  orderType?: null | string;
  /**
   * Validity
   */
  validity?: null | string;
  /**
   * Registered
   */
  registered?: null | string;
  /**
   * Sent
   */
  sent?: null | string;
  /**
   * Branch code
   */
  branchCode?: null | string;
  /**
   * Agency code
   */
  agencyCode?: null | string;
  /**
   * Last next key
   */
  lastNextKey?: null | string;
  /**
   * Fetch count
   */
  fetchCount?: null | number;
  /**
   * Is sent
   */
  isSent?: boolean;
  /**
   * Is registered
   */
  isRegistered?: boolean;
  [k: string]: any;
};
