/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr order place request schema
 */
export type DrOrderPlaceRequest = BaseRequest & {
  /**
   * Code
   */
  code: string;
  /**
   * Heg yn
   */
  hegYn?: null | string;
  /**
   * Reg yn
   */
  regYn?: null | string;
  /**
   * Password
   */
  password?: null | string;
  /**
   * Order type
   */
  orderType?: "MP" | "LO" | "ATO" | "MAK" | "MOK" | "ATC" | "MTL" | "ALL";
  /**
   * Order price
   */
  orderPrice: number;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType: "BUY" | "SELL" | "ALL";
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Order quantity
   */
  orderQuantity: number;
  /**
   * Order condition
   */
  orderCondition?: null | string;
  /**
   * Stop order price
   */
  stopOrderPrice?: null | string;
  /**
   * Min match quantity
   */
  minMatchQuantity?: null | string;
  [k: string]: any;
};
