/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr order place request schema
 */
export type DrOrderPlaceRequest = BaseRequest & {
  /**
   * Code
   */
  code?: string;
  /**
   * Heg yn
   */
  hegYn?: string;
  /**
   * Reg yn
   */
  regYn?: string;
  /**
   * Password
   */
  password?: string;
  /**
   * Order type
   */
  orderType?: string;
  /**
   * Order price
   */
  orderPrice?: number;
  /**
   * Sell buy type
   */
  sellBuyType?: string;
  /**
   * Account number
   */
  accountNumber?: string;
  /**
   * Order quantity
   */
  orderQuantity?: number;
  /**
   * Order condition
   */
  orderCondition?: string;
  /**
   * Stop order price
   */
  stopOrderPrice?: string;
  /**
   * Min match quantity
   */
  minMatchQuantity?: string;
  [k: string]: any;
};
