/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Dr order adv history request schema
 */
export type DrOrderAdvHistoryRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Password
   */
  password?: null | string;
  /**
   * Advance order type
   */
  advanceOrderType?: null | ("AO" | "CAO");
  /**
   * From date (YYYYmmdd)
   */
  fromDate?: null | string;
  /**
   * To date (YYYYmmdd)
   */
  toDate?: null | string;
  /**
   * Register type (0. ALL, 1: Edit or Modify, 2: Cancel)
   */
  registerType?: null | ("0" | "1" | "2");
  /**
   * Order send, (0. ALL, 1. Send, 2.Net send 3.Reject, 4.Cancel)
   */
  orderSend?: null | ("0" | "1" | "2" | "3" | "4");
  /**
   * Matched status
   */
  matchedStatus?: null | ("ALL" | "UNMATCHED" | "PARTIALLY_MATCHED" | "FULLY_MATCHED");
  /**
   * Validity
   */
  validity?: null | string;
  /**
   * Branch code
   */
  branchCode?: null | string;
  /**
   * Agency code
   */
  agencyCode?: null | string;
  /**
   * Contract code
   */
  contractCode?: null | string;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Roll over type, (0. All, 1. Roll Over CAO, 2. No Roll Over CAO)
   */
  rollOverType?: null | ("0" | "1" | "2");
  /**
   * Last next key
   */
  lastNextKey?: null | string;
  /**
   * Fetch count
   */
  fetchCount?: null | number;
  [k: string]: any;
};
