/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Query derivatives withdraw cash fee response schema
 */
export interface DrWithdrawCashFeeResponse {
  /**
   * fee Amount
   */
  feeAmount?: null | number;
  /**
   * payment On Behalf
   */
  paymentOnBehalf?: null | number;
  /**
   * adjusted Amount
   */
  adjustedAmount?: null | number;
  /**
   * fee Type
   */
  feeType?: null | string;
  [k: string]: any;
}
