/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Query derivatives withdraw cash fee request schema
 */
export type DrWithdrawCashFeeRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * source Bank
   */
  sourceBank?: null | string;
  /**
   * dest Bank
   */
  destBank?: null | string;
  /**
   * amount
   */
  amount?: null | number;
  [k: string]: any;
};
