/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Loan history request schema
 */
export type LoanHistoryRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Loan bank code
   */
  loanBankCode?: null | string;
  /**
   * Last loan date
   */
  lastLoanDate?: null | string;
  /**
   * Last loan bank code
   */
  lastLoanBankCode?: null | string;
  /**
   * Last match date
   */
  lastMatchDate?: null | string;
  /**
   * Last stock code
   */
  lastStockCode?: null | string;
  /**
   * Fetch count
   */
  fetchCount?: null | number;
  [k: string]: any;
};
