/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Loan detail response schema
 */
export interface LoanDetailResponse {
  /**
   * Tax
   */
  tax?: null | number;
  /**
   * Match date
   */
  matchDate?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Settle date
   */
  settleDate?: null | string;
  /**
   * Trading fee
   */
  tradingFee?: null | number;
  /**
   * Match amount
   */
  matchAmount?: null | number;
  /**
   * Adjust amount
   */
  adjustAmount?: null | number;
  /**
   * Loan order type
   */
  loanOrderType?: null | string;
  /**
   * Match quantity
   */
  matchQuantity?: null | number;
  /**
   * Possible amount
   */
  possibleAmount?: null | number;
  /**
   * Settle bank code
   */
  settleBankCode?: null | string;
  /**
   * Settle bank name
   */
  settleBankName?: null | string;
  [k: string]: any;
}
