/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Loan available response schema
 */
export interface LoanAvailableResponse {
  /**
   * Tax
   */
  tax?: null | number;
  /**
   * Fee rate
   */
  feeRate?: null | number;
  /**
   * Match date
   */
  matchDate?: null | string;
  /**
   * Loan period
   */
  loanPeriod?: null | number;
  /**
   * Settle date
   */
  settleDate?: null | string;
  /**
   * Trading fee
   */
  tradingFee?: null | number;
  /**
   * Match amount
   */
  matchAmount?: null | number;
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   * Adjust amount
   */
  adjustAmount?: null | number;
  /**
   * Estimated fee
   */
  estimatedFee?: null | number;
  /**
   * Loan bank name
   */
  loanBankName?: null | string;
  /**
   * Loan order name
   */
  loanOrderName?: null | string;
  /**
   * Loan order type
   */
  loanOrderType?: null | string;
  /**
   * Possible amount
   */
  possibleAmount?: null | number;
  /**
   * Settle bank code
   */
  settleBankCode?: null | string;
  [k: string]: any;
}
