/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Loan detail request schema
 */
export type LoanDetailRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Loan bank code
   */
  loanBankCode: null | string;
  /**
   * Settle bank code
   */
  settleBankCode?: null | string;
  /**
   * Match date
   */
  matchDate: null | string;
  /**
   * Settle date
   */
  settleDate: null | string;
  /**
   * Loan order type
   */
  loanOrderType: null | string;
  /**
   * Last settle bank code
   */
  lastSettleBankCode?: null | string;
  /**
   * Last stock code
   */
  lastStockCode?: null | string;
  /**
   * Last loan order type
   */
  lastLoanOrderType?: null | string;
  [k: string]: any;
};
