/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Loan banks response schema
 */
export interface LoanBanksResponse {
  /**
   * Bank code
   */
  bankCode?: null | string;
  /**
   * Bank name
   */
  bankName?: null | string;
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  [k: string]: any;
}
