/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Loan history response schema
 */
export interface LoanHistoryResponse {
  /**
   * Status
   */
  status?: null | string;
  /**
   * Loan date
   */
  loanDate?: null | string;
  /**
   * Match date
   */
  matchDate?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Loan amount
   */
  loanAmount?: null | number;
  /**
   * Match amount
   */
  matchAmount?: null | number;
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   * Loan bank code
   */
  loanBankCode?: null | string;
  /**
   * Loan bank name
   */
  loanBankName?: null | string;
  /**
   * Match quantity
   */
  matchQuantity?: null | number;
  /**
   * Loan repay amount
   */
  loanRepayAmount?: null | number;
  /**
   * Loan remain amount
   */
  loanRemainAmount?: null | number;
  [k: string]: any;
}
