/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Margin response schema
 */
export interface MarginResponse {
  /**
   * ratio
   */
  ratio?: number;
  [k: string]: any;
}
