/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Modify order request schema
 */
export type ModifyOrderRequest = BaseRequest & {
  /**
   * Bank code
   */
  bankCode?: null | string;
  /**
   * Bank name
   */
  bankName?: null | string;
  /**
   * Order type
   */
  orderType?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Branch code
   */
  branchCode?: null | string;
  /**
   * Market type, [HOSE, HNX, UPCOM, ALL]
   */
  marketType?: null | ("HOSE" | "HNX" | "UPCOM" | "ALL");
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * Bank account
   */
  bankAccount?: null | string;
  /**
   * Order number
   */
  orderNumber?: null | string;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Order quantity
   */
  orderQuantity?: null | number;
  /**
   * Securities type
   */
  securitiesType?: null | string;
  [k: string]: any;
};
