/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Modify order response schema
 */
export interface ModifyOrderResponse {
  /**
   * Type
   */
  type?: null | string;
  /**
   * Order number
   */
  orderNumber?: null | string;
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  [k: string]: any;
}
