/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Query order advance history response schema
 */
export interface OrderAdvanceHistoryResponse {
  /**
   * Channel
   */
  channel?: null | string;
  /**
   * Username
   */
  username?: null | string;
  /**
   * Order date
   */
  orderDate?: null | string;
  /**
   * Order time
   */
  orderTime?: null | string;
  /**
   * Order type
   */
  orderType?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Branch code
   */
  branchCode?: null | string;
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * Order number
   */
  orderNumber?: null | string;
  /**
   * Order status
   */
  orderStatus?: null | string;
  /**
   * Phone number
   */
  phoneNumber?: null | string;
  /**
   * Sell buy type
   */
  sellBuyType?: null | string;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Order quantity
   */
  orderQuantity?: null | number;
  [k: string]: any;
}
