/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * orderHistoryResponse schema
 */
export interface OrderHistoryResponse {
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Order date (YYYYmmdd)
   */
  orderDate?: null | string;
  /**
   * Order time (HHMMSS)
   */
  orderTime?: null | string;
  /**
   * Sell buy type, [BUY, SELL, ALL]
   */
  sellBuyType?: null | ("BUY" | "SELL" | "ALL");
  /**
   * Order type, [LO , MP , ATO , ATC , AON , BIG_LOT , MOK , MAK , MTL , IO , SO_GREATER , SO_LESS , SBO , OBO , PLO , ALL]
   */
  orderType?:
    | "LO"
    | "MP"
    | "ATO"
    | "ATC"
    | "AON"
    | "BIG_LOT"
    | "MOK"
    | "MAK"
    | "MTL"
    | "IO"
    | "SO_GREATER"
    | "SO_LESS"
    | "SBO"
    | "OBO"
    | "PLO"
    | "ALL";
  /**
   * Order quantity
   */
  orderQuantity?: null | number;
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * Order amount
   */
  orderAmount?: null | number;
  /**
   * Matched quantity
   */
  matchedQuantity?: null | number;
  /**
   * Matched price
   */
  matchedPrice?: null | number;
  /**
   * Matched amount
   */
  matchedAmount?: null | number;
  /**
   * Unmatched quantity
   */
  unmatchedQuantity?: null | number;
  /**
   * Modify cancel type, [NORMAL, PARTIAL_CORRECTION, ALL_CORRECTION, PARTIAL_CANCEL, ALL_CANCEL]
   */
  modifyCancelType?: "NORMAL" | "PARTIAL_CORRECTION" | "ALL_CORRECTION" | "PARTIAL_CANCEL" | "ALL_CANCEL";
  /**
   * Modify cancel quantity
   */
  modifyCancelQuantity?: null | number;
  /**
   * Order status, [RECEIPT, SEND, ORDER_CONFIRM, RECEIPT_CONFIRM, FULL_FILLED, PARTIAL_FILLED, REJECT]
   */
  orderStatus?: "RECEIPT" | "SEND" | "ORDER_CONFIRM" | "RECEIPT_CONFIRM" | "FULL_FILLED" | "PARTIAL_FILLED" | "REJECT";
  /**
   * Order number
   */
  orderNumber?: null | string;
  /**
   * Original order number
   */
  originalOrderNumber?: null | string;
  /**
   * Username
   */
  username?: null | string;
  /**
   * Branch code
   */
  branchCode?: null | string;
  /**
   * Bank name
   */
  bankName?: null | string;
  [k: string]: any;
}
