/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Query order advance history request schema
 */
export type OrderAdvanceHistoryRequest = BaseRequest & {
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Market type
   */
  marketType?: null | string;
  /**
   * Sell buy type
   */
  sellBuyType?: null | string;
  /**
   * Last order date
   */
  lastOrderDate?: null | string;
  /**
   * Last order number
   */
  lastOrderNumber?: null | string;
  /**
   * Fetch count
   */
  fetchCount?: null | number;
  [k: string]: any;
};
