/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Order modify all request schema
 */
export type OrderModifyAllRequest = BaseRequest & {
  /**
   * Order type
   */
  orderType?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Market type
   */
  marketType?: null | string;
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * Bank account
   */
  bankAccount?: null | string;
  /**
   * Sell buy type
   */
  sellBuyType?: null | string;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * New order price
   */
  newOrderPrice?: null | number;
  /**
   * Securities type
   */
  securitiesType?: null | string;
  [k: string]: any;
};
