/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Query order today unmatch response schema
 */
export interface OrderTodayUnmatchResponse {
  /**
   * Channel
   */
  channel?: null | string;
  /**
   * Bank code
   */
  bankCode?: null | string;
  /**
   * Bank name
   */
  bankName?: null | string;
  /**
   * Username
   */
  username?: null | string;
  /**
   * Order date
   */
  orderDate?: null | string;
  /**
   * Order time
   */
  orderTime?: null | string;
  /**
   * Order type
   */
  orderType?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Branch code
   */
  branchCode?: null | string;
  /**
   * Market type
   */
  marketType?: null | string;
  /**
   * Order price
   */
  orderPrice?: null | number;
  /**
   * Order number
   */
  orderNumber?: null | string;
  /**
   * Order status
   */
  orderStatus?: null | string;
  /**
   * Sell buy type
   */
  sellBuyType?: null | string;
  /**
   * Matched price
   */
  matchedPrice?: null | number;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Matched amount
   */
  matchedAmount?: null | number;
  /**
   * Order quantity
   */
  orderQuantity?: null | number;
  /**
   * Matched quantity
   */
  matchedQuantity?: null | number;
  /**
   * Unmatched quantity
   */
  unmatchedQuantity?: null | number;
  /**
   * Original order number
   */
  originalOrderNumber?: null | string;
  [k: string]: any;
}
