/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Rights register request schema
 */
export type RightsRegisterRequest = BaseRequest & {
  /**
   * Amount
   */
  amount?: null | number;
  /**
   * Bank code
   */
  bankCode?: null | string;
  /**
   * Base date
   */
  baseDate?: null | string;
  /**
   * Quantity
   */
  quantity?: null | number;
  /**
   * Right type
   */
  rightType?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Bank account
   */
  bankAccount?: null | string;
  /**
   * Trade number
   */
  tradeNumber?: null | string;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Sequence number
   */
  sequenceNumber?: null | number;
  [k: string]: any;
};
