/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Rights detail response schema
 */
export interface RightsDetailResponse {
  /**
   * Amount
   */
  amount?: null | number;
  /**
   * End date
   */
  endDate?: null | number;
  /**
   * Quantity
   */
  quantity?: null | string;
  /**
   * Right type
   */
  rightType?: null | number;
  /**
   * Start date
   */
  startDate?: null | number;
  /**
   * Issue price
   */
  issuePrice?: null | number;
  /**
   * Trade number
   */
  tradeNumber?: null | string;
  /**
   * Available amount
   */
  availableAmount?: null | number;
  /**
   * Standard quantity
   */
  standardQuantity?: null | number;
  /**
   * Available quantity
   */
  availableQuantity?: null | number;
  /**
   * Process status code
   */
  processStatusCode?: null | number;
  /**
   * Process status name
   */
  processStatusName?: null | number;
  /**
   * Approve waiting quantity
   */
  approveWaitingQuantity?: null | number;
  /**
   * Bank cancel waiting quantity
   */
  bankCancelWaitingQuantity?: null | number;
  /**
   * Bank approve waiting quantity
   */
  bankApproveWaitingQuantity?: null | number;
  [k: string]: any;
}
