/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Rights detail request schema
 */
export type RightsDetailRequest = BaseRequest & {
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Base date
   */
  baseDate?: null | string;
  /**
   * Right type
   */
  rightType?: null | string;
  /**
   * Sequence number
   */
  sequenceNumber?: null | number;
  /**
   * Bank code
   */
  bankCode?: null | string;
  /**
   * Bank account
   */
  bankAccount?: null | string;
  /**
   * Bank name
   */
  bankName?: null | string;
  [k: string]: any;
};
