/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Rights available response schema
 */
export interface RightsAvailableResponse {
  /**
   * Note
   */
  note?: null | string;
  /**
   * End date
   */
  endDate?: null | string;
  /**
   * Base date
   */
  baseDate?: null | string;
  /**
   * Start date
   */
  startDate?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Stock name
   */
  stockName?: null | string;
  /**
   * Issue price
   */
  issuePrice?: null | number;
  /**
   * Right status
   */
  rightStatus?: null | string;
  /**
   * Sequence number
   */
  sequenceNumber?: null | number;
  /**
   * Available quantity
   */
  availableQuantity?: null | number;
  [k: string]: any;
}
