/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Rights others response schema
 */
export interface RightsOthersResponse {
  /**
   * Base date
   */
  baseDate?: null | string;
  /**
   * Right name
   */
  rightName?: null | string;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Receipt date
   */
  receiptDate?: null | string;
  /**
   * Dividend date
   */
  dividendDate?: null | string;
  /**
   * Dividend amount
   */
  dividendAmount?: null | number;
  /**
   * Receipt quantity
   */
  receiptQuantity?: null | number;
  [k: string]: any;
}
