/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Order oddlot sellable response schema
 */
export interface StockOrderOddlotSellableResponse {
  /**
   * T1 buy
   */
  t1Buy?: null | number;
  /**
   * T2 buy
   */
  t2Buy?: null | number;
  /**
   * T3 buy
   */
  t3Buy?: null | number;
  /**
   * T1 sell
   */
  t1Sell?: null | number;
  /**
   * T2 sell
   */
  t2Sell?: null | number;
  /**
   * T3 sell
   */
  t3Sell?: null | number;
  /**
   * Today buy
   */
  todayBuy?: null | number;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Today sell
   */
  todaySell?: null | number;
  /**
   * Today order
   */
  todayOrder?: null | number;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Balance quantity
   */
  balanceQuantity?: null | number;
  /**
   * Sellable quantity
   */
  sellableQuantity?: null | number;
  [k: string]: any;
}
