/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Cancel order request schema
 */
export type StockOrderCancelRequest = BaseRequest & {
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Branch code
   */
  branchCode: string;
  /**
   * Order number
   */
  orderNumber: string;
  /**
   * Account number
   */
  accountNumber: string;
  [k: string]: any;
};
