/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Transfer cash history response schema
 */
export interface TransferCashHistoryResponse {
  /**
   * Note
   */
  note?: null | string;
  /**
   * Amount
   */
  amount?: null | number;
  /**
   * Is cancel
   */
  isCancel?: boolean;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Sequence number
   */
  sequenceNumber?: null | number;
  /**
   * Transaction date
   */
  transactionDate?: null | string;
  /**
   * Received sub number
   */
  receivedSubNumber?: null | string;
  /**
   * Send sequence number
   */
  sendSequenceNumber?: null | number;
  /**
   * Received account name
   */
  receivedAccountName?: null | string;
  /**
   * Receive sequence number
   */
  receiveSequenceNumber?: null | number;
  /**
   * Received account number
   */
  receivedAccountNumber?: null | string;
  /**
   * Transfer sequence number
   */
  transferSequenceNumber?: null | number;
  [k: string]: any;
}
