/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Transfer stock history response schema
 */
export interface TransferStockHistoryResponse {
  /**
   * Note
   */
  note?: null | string;
  /**
   * Quantity
   */
  quantity?: null | number;
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Account number
   */
  accountNumber?: null | string;
  /**
   * Sequence number
   */
  sequenceNumber?: null | string;
  /**
   * Limited quantity
   */
  limitedQuantity?: null | number;
  /**
   * Transaction date
   */
  transactionDate?: null | string;
  /**
   * Received sub number
   */
  receivedSubNumber?: null | string;
  /**
   * Received account number
   */
  receivedAccountNumber?: null | string;
  [k: string]: any;
}
