/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Transfer im withdraw info response schema
 */
export interface TransferImWithdrawInfoResponse {
  /**
   * total remaining unread notification
   */
  totalUnread?: null | number;
  /**
   * Deposit amount
   */
  depositAmount?: null | number;
  /**
   * Available amount
   */
  availableAmount?: null | number;
  /**
   * Collateral amount
   */
  collateralAmount?: null | number;
  /**
   * Other block amount
   */
  otherBlockAmount?: null | number;
  /**
   * Settle block amount
   */
  settleBlockAmount?: null | number;
  /**
   * Deposit block amount
   */
  depositBlockAmount?: null | number;
  /**
   * Withdraw block amount
   */
  withdrawBlockAmount?: null | number;
  [k: string]: any;
}
