/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Cancel transfer cash request schema
 */
export type TransferCashCancelRequest = BaseRequest & {
  /**
   * Note
   */
  note?: null | string;
  /**
   * Amount
   */
  amount: number;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Account number
   */
  accountNumber: string;
  /**
   * Sequence number
   */
  sequenceNumber: string;
  /**
   * Received sub number
   */
  receivedSubNumber: string;
  /**
   * Send sequence number
   */
  sendSequenceNumber: string;
  /**
   * Receive sequence number
   */
  receiveSequenceNumber: string;
  /**
   * Received account number
   */
  receivedAccountNumber: string;
  [k: string]: any;
};
