/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Transfer stock balance response schema
 */
export interface TransferStockBalanceResponse {
  /**
   * Stock code
   */
  stockCode?: null | string;
  /**
   * Stock name
   */
  stockName?: null | string;
  /**
   * Available quantity
   */
  availableQuantity?: null | number;
  /**
   * Limit available quantity
   */
  limitAvailableQuantity?: null | number;
  [k: string]: any;
}
