/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {Account} from "./Account";

/**
 * user info in token
 */
export interface UserInfo {
  username?: string;
  userLevel?: string;
  accounts?: {
    [k: string]: Account;
  }[];
  [k: string]: any;
}
