/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * Withdraw request request schema
 */
export type WithdrawRequestRequest = BaseRequest & {
  /**
   * Note
   */
  note?: null | string;
  /**
   * Amount
   */
  amount?: null | number;
  /**
   * Bank code
   */
  bankCode?: null | string;
  /**
   * Sub number
   */
  subNumber?: null | string;
  /**
   * Bank account
   */
  bankAccount?: null | string;
  /**
   * Account number
   */
  accountNumber?: null | string;
  [k: string]: any;
};
