/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Withdraw banks response schema
 */
export interface WithdrawBanksResponse {
  /**
   * Bank code
   */
  bankCode?: null | string;
  /**
   * Bank name
   */
  bankName?: null | string;
  /**
   * Bank account name
   */
  bankAccountName?: null | string;
  /**
   * Bank account number
   */
  bankAccountNumber?: null | string;
  [k: string]: any;
}
