/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Withdraw history response schema
 */
export interface WithdrawHistoryResponse {
  /**
   * Bank
   */
  bank?: null | string;
  /**
   * Note
   */
  note?: null | string;
  /**
   * Amount
   */
  amount?: null | number;
  /**
   * Approver
   */
  approver?: null | string;
  /**
   * Bank code
   */
  bankCode?: null | string;
  /**
   * Bank name
   */
  bankName?: null | string;
  /**
   * Is cancel
   */
  isCancel?: boolean;
  /**
   * Bank account
   */
  bankAccount?: null | string;
  /**
   * Approval date
   */
  approvalDate?: null | string;
  /**
   * Sequence number
   */
  sequenceNumber?: null | number;
  /**
   * Transaction code
   */
  transactionCode?: null | string;
  /**
   * Transaction date
   */
  transactionDate?: null | string;
  /**
   * Transaction type
   */
  transactionType?: null | string;
  /**
   * Transaction sequence number
   */
  transactionSequenceNumber?: null | number;
  [k: string]: any;
}
