/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * etfIndexDailyResponse schema
 */
export interface EtfIndexDailyResponse {
  /**
   * code
   */
  cd?: string;
  /**
   * date
   */
  d?: string;
  /**
   * open
   */
  o?: number;
  /**
   * high
   */
  h?: number;
  /**
   * low
   */
  l?: number;
  /**
   * last
   */
  c?: number;
  /**
   * change
   */
  ch?: number;
  /**
   * rate
   */
  r?: number;
  [k: string]: any;
}
