/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * foreignerDailyResponse schema
 */
export interface ForeignerDailyResponse {
  /**
   * ForeignerBuyVolume
   */
  bv?: number;
  /**
   * ForeignerSellVolume
   */
  sv?: number;
  /**
   * ForeignerTotalRoom
   */
  tr?: number;
  /**
   * ForeignerCurrentRoom
   */
  cr?: number;
  /**
   * ForeignerBuyAbleRatio
   */
  br?: number;
  /**
   * ForeignerChangeVolume
   */
  cv?: number;
  /**
   * ForeignerHoldVolume
   */
  hv?: number;
  /**
   * ForeignerHoldRatio
   */
  hr?: number;
  [k: string]: any;
}
