/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * marketLiquidityResponse schema
 */
export interface MarketLiquidityResponse {
  /**
   * properties name is date (YYYYMMDD), each item is an array contain 2 value, minute (string) and liquidity (number)
   */
  [k: string]: [] | [string] | [string, number];
}
