/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * marketSessionStatusResponse schema
 */
export interface MarketSessionStatusResponse {
  /**
   * market: ALL, HNX, HOSE, UPCOM
   */
  market?: "ALL" | "HNX" | "HOSE" | "UPCOM";
  /**
   * status: ATO, LO, INTERMISSION, ATC, PLO, CLOSED, RUNOFF
   */
  status?: "ATO" | "LO" | "INTERMISSION" | "ATC" | "PLO" | "CLOSED" | "RUNOFF";
  /**
   * time , example: 074500 - (hhmmss)
   */
  time?: string;
  /**
   * last trading date (YYYYMMDD)
   */
  lastTradingDate?: string;
  /**
   * previous trading date (YYYYMMDD)
   */
  previousTradingDate?: string;
  /**
   * type: EQUITY, DERIVATIVES
   */
  type?: "EQUITY" | "DERIVATIVES";
  [k: string]: any;
}
