/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * putthroughAdvertiseResponse schema
 */
export interface PutthroughAdvertiseResponse {
  /**
   * code
   */
  c?: string;
  /**
   * time (yyyyMMdd)
   */
  t?: string;
  /**
   * sec Id
   */
  s?: string;
  /**
   * trader Id
   */
  ti?: string;
  /**
   * sell Buy Type
   */
  sb?: string;
  /**
   * price
   */
  p?: number;
  /**
   * quantity
   */
  q?: number;
  /**
   * put through volume
   */
  pv?: number;
  /**
   * put through value
   */
  pt?: number;
  /**
   * contact
   */
  ct?: string;
  /**
   * is Cancel
   */
  ic?: boolean;
  [k: string]: any;
}
