/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * putthroughDealResponse schema
 */
export interface PutthroughDealResponse {
  /**
   * code
   */
  c?: string;
  /**
   * time (yyyyMMdd)
   */
  t?: string;
  /**
   * confirm Number
   */
  cn?: string;
  /**
   * match Price
   */
  mp?: string;
  /**
   * match Volume
   */
  mv?: string;
  /**
   * put through volume
   */
  pv?: number;
  /**
   * put through value
   */
  pt?: number;
  /**
   * is Cancel
   */
  ic?: boolean;
  [k: string]: any;
}
