/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * stockRankingUpDownResponse schema
 */
export interface StockRankingUpDownResponse {
  /**
   * HNX
   */
  HNX?: {
    /**
     * marketType
     */
    mt?: string;
    /**
     * code
     */
    cd?: string;
    /**
     * ceiling Floor Equal
     */
    cl?: string;
    /**
     * date (yyyyMMdd)
     */
    d?: string;
    /**
     * open
     */
    o?: number;
    /**
     * high
     */
    h?: number;
    /**
     * low
     */
    l?: number;
    /**
     * last
     */
    c?: number;
    /**
     * change
     */
    ch?: number;
    /**
     * rate
     */
    r?: number;
    /**
     * trading Volume
     */
    tv?: number;
    /**
     * trading Value
     */
    tr?: number;
    /**
     * up Down Change
     */
    uc?: number;
    /**
     * up Down Rate
     */
    ur?: number;
    /**
     * start Price
     */
    sp?: number;
    /**
     * end Price
     */
    ep?: number;
    [k: string]: any;
  }[];
  /**
   * HOSE
   */
  HOSE?: {
    /**
     * marketType
     */
    mt?: string;
    /**
     * code
     */
    cd?: string;
    /**
     * ceiling Floor Equal
     */
    cl?: string;
    /**
     * date
     */
    d?: string;
    /**
     * open
     */
    o?: number;
    /**
     * high
     */
    h?: number;
    /**
     * low
     */
    l?: number;
    /**
     * last
     */
    c?: number;
    /**
     * change
     */
    ch?: number;
    /**
     * rate
     */
    r?: number;
    /**
     * trading Volume
     */
    tv?: number;
    /**
     * trading Value
     */
    tr?: number;
    /**
     * up Down Change
     */
    uc?: number;
    /**
     * up Down Rate
     */
    ur?: number;
    /**
     * start Price
     */
    sp?: number;
    /**
     * end Price
     */
    ep?: number;
    [k: string]: any;
  }[];
  /**
   * UPCOM
   */
  UPCOM?: {
    /**
     * marketType
     */
    mt?: string;
    /**
     * code
     */
    cd?: string;
    /**
     * ceiling Floor Equal
     */
    cl?: string;
    /**
     * date
     */
    d?: string;
    /**
     * open
     */
    o?: number;
    /**
     * high
     */
    h?: number;
    /**
     * low
     */
    l?: number;
    /**
     * last
     */
    c?: number;
    /**
     * change
     */
    ch?: number;
    /**
     * rate
     */
    r?: number;
    /**
     * trading Volume
     */
    tv?: number;
    /**
     * trading Value
     */
    tr?: number;
    /**
     * up Down Change
     */
    uc?: number;
    /**
     * up Down Rate
     */
    ur?: number;
    /**
     * start Price
     */
    sp?: number;
    /**
     * end Price
     */
    ep?: number;
    [k: string]: any;
  }[];
  [k: string]: any;
}
