/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * stockRankingTradeResponse schema
 */
export interface StockRankingTradeResponse {
  /**
   * code
   */
  c?: string;
  /**
   * last
   */
  l?: number;
  /**
   * change
   */
  cn?: number;
  /**
   * rate
   */
  r?: number;
  /**
   * trading Volume
   */
  tv?: number;
  /**
   * trading Value
   */
  tr?: number;
  /**
   * turnover Rate
   */
  to?: number;
  [k: string]: any;
}
