/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * stockRankingTopResponse schema
 */
export interface StockRankingTopResponse {
  /**
   * marketType
   */
  mt?: string;
  /**
   * code
   */
  cd?: string;
  /**
   * ceiling Floor Equal
   */
  cl?: string;
  /**
   * date (yyyyMMdd)
   */
  d?: string;
  /**
   * open
   */
  o?: number;
  /**
   * high
   */
  h?: number;
  /**
   * low
   */
  l?: number;
  /**
   * last
   */
  c?: number;
  /**
   * change
   */
  ch?: number;
  /**
   * rate
   */
  r?: number;
  /**
   * trading Volume
   */
  tv?: number;
  /**
   * trading Value
   */
  tr?: number;
  /**
   * power indicator
   */
  pi?: number;
  [k: string]: any;
}
