/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * symbolStaticInfoRequest schema
 */
export type SymbolStaticInfoRequest = BaseRequest & {
  /**
   * list symbol to filter (default query all symbol)
   */
  symbolList?: string[];
  /**
   * using for query next. (query symbol that has code < lastCode)
   */
  lastCode?: string;
  /**
   * The number of record that user want to see at each page, default 100
   */
  fetchCount?: number | null;
  [k: string]: any;
};
