/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * symbolQuoteRequest schema
 */
export type SymbolQuoteRequest = BaseRequest & {
  /**
   * symbol code
   */
  symbol: string;
  /**
   * query records with last trading volume smaller than this. Act as next key
   */
  lastTradingVolume?: number | null;
  /**
   * The number of record that user want to see at each page
   */
  fetchCount?: number | null;
  [k: string]: any;
};
