/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * symbolStaticInfoResponse schema
 */
export interface SymbolStaticInfoResponse {
  /**
   * symbol code
   */
  s?: string;
  /**
   * name
   */
  n1?: string;
  /**
   * english name
   */
  n2?: string;
  /**
   * market type
   */
  m?: "HOSE" | "HNX" | "UPCOM";
  /**
   * type: INDEX/STOCK/FUTURES/CW
   */
  t?: "INDEX" | "STOCK" | "FUTURES" | "CW";
  /**
   * reference price
   */
  re?: number;
  /**
   * ceiling price
   */
  ce?: number;
  /**
   * floor price
   */
  fl?: number;
  /**
   * first trade date (YYYYMMDD)
   */
  ftd?: string;
  /**
   * last trade date (YYYYMMDD)
   */
  ltd?: string;
  /**
   * maturity date (YYYYMMDD)
   */
  md?: string;
  /**
   * underlying symbol
   */
  ud?: string;
  /**
   * base code
   */
  b?: string;
  /**
   * base code securities type (INDEX/BOND)
   */
  bs?: "INDEX" | "BOND";
  /**
   * is highlight
   */
  i?: boolean;
  [k: string]: any;
}
