/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * symbolQuoteTickRequest schema
 */
export type SymbolQuoteTickRequest = BaseRequest & {
  /**
   * symbol code
   */
  symbol: string;
  /**
   * tick unit
   */
  tickUnit: number;
  /**
   * from sequence
   */
  fromSequence?: number | null;
  /**
   * to sequence
   */
  toSequence?: number | null;
  /**
   * The number of record that user want to see at each page
   */
  fetchCount?: number | null;
  [k: string]: any;
};
