/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * symbolTickSizeMatchResponse schema
 */
export type SymbolTickSizeMatchResponse = {
  /**
   * price
   */
  p?: number;
  /**
   * total matchingVolume
   */
  mv?: number;
  [k: string]: any;
}[];
