/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * symbolQuoteMinuteRequest schema
 */
export type SymbolQuoteMinuteRequest = BaseRequest & {
  /**
   * symbol code
   */
  symbol: string;
  /**
   * minute unit
   */
  minuteUnit: number;
  /**
   * from time (yyyyMMddhhmmss)
   */
  fromTime?: string | null;
  /**
   * to time (yyyyMMddhhmmss)
   */
  toTime?: string | null;
  /**
   * The number of record that user want to see at each page
   */
  fetchCount?: number | null;
  [k: string]: any;
};
