/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * symbolInfoResponse schema
 */
export interface SymbolInfoResponse {
  /**
   * symbol code
   */
  s?: string;
  /**
   * name
   */
  n?: string;
  /**
   * English name
   */
  ne?: string;
  /**
   * type
   */
  t?: string;
  /**
   * market Type
   */
  mt?: string;
  /**
   * last
   */
  c?: number;
  /**
   * open
   */
  o?: number;
  /**
   * high
   */
  h?: number;
  /**
   * low
   */
  l?: number;
  /**
   * change
   */
  ch?: number;
  /**
   * rate
   */
  r?: number;
  /**
   * Trading Volume
   */
  tv?: number;
  /**
   * Trading Value
   */
  tr?: number;
  /**
   * Date
   */
  d?: string;
  /**
   * time (yyyyMMddhhmmss)
   */
  ti?: string;
  /**
   * priority Trading Volume
   */
  ptv?: number;
  /**
   * reference code
   */
  rc?: string;
  /**
   * ceiling Price
   */
  cp?: number;
  /**
   * floor Price
   */
  fp?: number;
  /**
   * ceiling Floor Equal
   */
  ce?: string;
  /**
   * reference Price
   */
  rp?: number;
  /**
   * average Price
   */
  ap?: number;
  /**
   * high Time (yyyyMMddhhmmss)
   */
  ht?: string;
  /**
   * low Time (yyyyMMddhhmmss)
   */
  lt?: string;
  /**
   * putthrough volume
   */
  pv?: number;
  /**
   * total Trading Value
   */
  ttva?: number;
  /**
   * turnover Rate
   */
  tor?: number;
  /**
   * total Trading Volume
   */
  ttvo?: number;
  /**
   * listed Quantity
   */
  lq?: number;
  /**
   * project Open
   */
  po?: number;
  /**
   * control Code
   */
  cc?: string;
  /**
   * high Price 52 Week
   */
  hpw?: number;
  /**
   * low Price 52 Week
   */
  lpw?: number;
  /**
   * bid Price
   */
  bp?: number;
  /**
   * offer Price
   */
  op?: number;
  /**
   * total Bid Volume
   */
  tbv?: number;
  /**
   * total Offer Volume
   */
  tov?: number;
  /**
   * change Of Total Bid Volume
   */
  ctbv?: number;
  /**
   * change Of Total Offer Volume
   */
  ctov?: number;
  /**
   * different Bid Offer
   */
  dbo?: number;
  /**
   * accumulate Bid Volume
   */
  abv?: number;
  /**
   * accumulate Bid Count
   */
  abc?: number;
  /**
   * accumulate Offer Volume
   */
  aov?: number;
  /**
   * accumulate Offer Count
   */
  aoc?: number;
  /**
   * industry
   */
  i?: string;
  /**
   * match By
   */
  mb?: string;
  /**
   * match Volume
   */
  mv?: number;
  /**
   * up Count
   */
  uc?: number;
  /**
   * ceiling Count
   */
  cec?: number;
  /**
   * down Count
   */
  dc?: number;
  /**
   * floor Count
   */
  fc?: number;
  /**
   * unchanged Count
   */
  ucc?: number;
  /**
   * is Highlight
   */
  ih?: number;
  /**
   * total Bid Count
   */
  tbc?: number;
  /**
   * total Offer Count
   */
  toc?: number;
  /**
   * issuer Name
   */
  in?: string;
  /**
   * exercise Price
   */
  ecp?: number;
  /**
   * exercise Ratio
   */
  er?: string;
  /**
   * break Even
   */
  be?: number;
  /**
   * implied Volatility
   */
  iv?: number;
  /**
   * parity
   */
  pt?: number;
  /**
   * maturity Date
   */
  md?: number;
  /**
   * theory price
   */
  tp?: number;
  /**
   * delta
   */
  dt?: number;
  /**
   * gearing ratio
   */
  gr?: number;
  /**
   * capital Fulcrum Point
   */
  cfp?: number;
  /**
   * underlying Symbol
   */
  uls?: string;
  /**
   * underlying Price
   */
  ulp?: number;
  /**
   * underlying Change
   */
  ulc?: number;
  /**
   * underlying Rate
   */
  ulr?: number;
  /**
   * putthrough Value
   */
  pva?: number;
  /**
   * last Trading Time (yyyyMMdd hhmmss)
   */
  ltt?: string;
  /**
   * bid Volume
   */
  bvo?: number;
  /**
   * offer Volume
   */
  ov?: number;
  /**
   * expected Price
   */
  ep?: number;
  /**
   * session
   */
  ses?: string;
  /**
   * priority Volume
   */
  pvo?: number;
  /**
   * putthrough Trading Value
   */
  ptva?: number;
  /**
   * par Value
   */
  parv?: number;
  /**
   * foreigner Buy Volume
   */
  fbv?: number;
  /**
   * foreigner Sell Volume
   */
  fsv?: number;
  /**
   * foreigner Total Room
   */
  ftr?: number;
  /**
   * foreigner Current Room
   */
  fcr?: number;
  /**
   * market Name
   */
  mn?: string;
  /**
   * rights
   */
  rg?: string;
  /**
   * base Code
   */
  bc?: string;
  /**
   * base Code Securities Type
   */
  bcst?: string;
  /**
   * open Interest
   */
  oi?: number;
  /**
   * open Interest Change
   */
  oic?: number;
  /**
   * normal Foreigner BuyVolume
   */
  nfbvo?: number;
  /**
   * normal Foreigner BuyValue
   */
  nfbva?: number;
  /**
   * normal Foreigner Sell Volume
   */
  nfsvo?: number;
  /**
   * normal Foreigner Sell Value
   */
  nfsva?: number;
  /**
   * putthrough Foreigner Total Buy Volume
   */
  pftbvo?: number;
  /**
   * putthrough Foreigner Total Buy Value
   */
  pftbva?: number;
  /**
   * putthrough Foreigner Total Sell Volume
   */
  pftsvo?: number;
  /**
   * putthrough Foreigner Total Sell Value
   */
  pftsva?: number;
  /**
   * first Trading Date (yyyyMMdd)
   */
  ftd?: string;
  /**
   * end Trading Date (yyyyMMdd)
   */
  etd?: string;
  /**
   * remain Date (yyyyMMdd)
   */
  rd?: number;
  /**
   * theory Price
   */
  thp?: number;
  /**
   * basis
   */
  bs?: number;
  /**
   * theory Basis
   */
  thb?: number;
  /**
   * market Basis
   */
  mbs?: number;
  /**
   * disparate
   */
  dp?: number;
  /**
   * disparate Rate
   */
  dpr?: number;
  /**
   * start Date (yyyyMMdd)
   */
  sd?: string;
  /**
   * end Date (yyyyMMdd)
   */
  end?: string;
  [k: string]: any;
}
