/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * symbolPeriodResponse schema
 */
export interface SymbolPeriodResponse {
  /**
   * open price
   */
  o?: number;
  /**
   * high price
   */
  h?: number;
  /**
   * low price
   */
  l?: number;
  /**
   * close price
   */
  c?: number;
  /**
   * change
   */
  ch?: number;
  /**
   * rate
   */
  ra?: number;
  /**
   * trading volume
   */
  vo?: number;
  /**
   * trading value
   */
  va?: number;
  /**
   * day count
   */
  dc?: number;
  /**
   * date (YYYYMMDD)
   */
  d?: string;
  [k: string]: any;
}
