/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * topAiRatingRequest schema
 */
export type TopAiRatingRequest = BaseRequest & {
  /**
   * The number of record that user want to see at each page
   */
  fetchCount?: number | null;
  /**
   * last code from previous query
   */
  nextKey?: string | null;
  [k: string]: any;
};
