/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * topAiRatingResponse schema
 */
export type TopAiRatingResponse = {
  /**
   * code
   */
  code?: string;
  /**
   * date
   */
  date?: string;
  /**
   * techScore
   */
  techScore?: number;
  /**
   * valuationScore
   */
  valuationScore?: number;
  /**
   * gsScore
   */
  gsScore?: number;
  /**
   * overall
   */
  overall?: number;
  /**
   * price
   */
  price?: number;
  /**
   * change
   */
  change?: number;
  [k: string]: any;
}[];
