/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * topForeignerTradingResponse schema
 */
export interface TopForeignerTradingResponse {
  /**
   * symbol code
   */
  s?: string;
  /**
   * marketType
   */
  mt?: string;
  /**
   * open
   */
  o?: number;
  /**
   * high
   */
  h?: number;
  /**
   * low
   */
  l?: number;
  /**
   * last
   */
  c?: number;
  /**
   * change
   */
  ch?: number;
  /**
   * rate
   */
  ra?: number;
  /**
   * trading Volume
   */
  vo?: number;
  /**
   * trading Value
   */
  va?: number;
  /**
   * foreigner buy value
   */
  fbv?: number;
  /**
   * foreigner sell value
   */
  fsv?: number;
  /**
   * foreigner net trading value (buy value - sell value)
   */
  fnv?: number;
  [k: string]: any;
}
