/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * tradingViewLoadChartResponse schema
 */
export interface TradingViewLoadChartResponse {
  /**
   * status
   */
  status?: string;
  /**
   * data
   */
  data?: {
    /**
     * id
     */
    id?: string;
    /**
     * timestamp
     */
    timestamp?: number;
    /**
     * name
     */
    name?: string;
    /**
     * content
     */
    content?: string;
    [k: string]: any;
  };
  /**
   * message
   */
  message?: string;
  [k: string]: any;
}
