/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * tradingViewSaveChartRequest schema
 */
export type TradingViewSaveChartRequest = BaseRequest & {
  /**
   * client
   */
  client: string;
  /**
   * user
   */
  user: string;
  /**
   * name
   */
  name: string;
  /**
   * symbol
   */
  symbol: string;
  /**
   * content
   */
  content: string;
  /**
   * resolution
   */
  resolution: string;
  [k: string]: any;
};
