/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * tradingViewHistoryRequest schema
 */
export type TradingViewHistoryRequest = BaseRequest & {
  /**
   * symbol Code
   */
  symbol: string;
  /**
   * from time, in millisecond / 1000, like 1586933880, 10 number
   */
  from: number;
  /**
   * to time, in millisecond / 1000, like 1586933880, 10 number
   */
  to: number;
  /**
   * resolution, for minute: ['1','3','5','10','15','30','60'], for daily, 'D'
   */
  resolution: string;
  /**
   * Fetch count, default 300 for chart
   */
  fetchCount?: null | number;
  /**
   * datetime of last received record, in millisecond / 1000, like 1586933880, 10 number
   */
  lastTime?: null | number;
  [k: string]: any;
};
