/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "../common";

/**
 * tradingViewHistoryRequest schema
 */
export type TradingViewHistoryRequest = BaseRequest & {
  /**
   * symbol Code
   */
  symbol?: string;
  /**
   * from
   */
  from: number;
  /**
   * to
   */
  to: number;
  /**
   * resolution
   */
  resolution: string;
  [k: string]: any;
};
