/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * tradingViewSymbolSearchRequest schema
 */
export type TradingViewSymbolSearchRequest = BaseRequest & {
  /**
   * symbol Code
   */
  query: string;
  /**
   * type
   */
  type: string;
  /**
   * exchange
   */
  exchange: string;
  /**
   * limit
   */
  limit: number;
  [k: string]: any;
};
