/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * tradingViewSymbolInfoResponse schema
 */
export interface TradingViewSymbolInfoResponse {
  /**
   * symbol
   */
  symbol?: string;
  /**
   * full_name
   */
  full_name?: string;
  /**
   * description
   */
  description?: string;
  /**
   * exchange
   */
  exchange?: string;
  /**
   * type
   */
  type?: string;
  [k: string]: any;
}
